{
  "compatibilityLevel": 1600,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"diabetic_data\",\"Fato_Intenacao\",\"Dim_Paciente\",\"Dim_Admissao\",\"Dim_Clinico\",\"Dim_Tratamento\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.132.1053.0 (24.08)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "diabetic_data",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\geova\\OneDrive - UniCEUB\\Projeto_Final_BI_II\\dados\\diabetic_data.csv\"),[Delimiter=\",\", Columns=50, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
          "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"encounter_id\", Int64.Type}, {\"patient_nbr\", Int64.Type}, {\"race\", type text}, {\"gender\", type text}, {\"age\", type text}, {\"weight\", type text}, {\"admission_type_id\", Int64.Type}, {\"discharge_disposition_id\", Int64.Type}, {\"admission_source_id\", Int64.Type}, {\"time_in_hospital\", Int64.Type}, {\"payer_code\", type text}, {\"medical_specialty\", type text}, {\"num_lab_procedures\", Int64.Type}, {\"num_procedures\", Int64.Type}, {\"num_medications\", Int64.Type}, {\"number_outpatient\", Int64.Type}, {\"number_emergency\", Int64.Type}, {\"number_inpatient\", Int64.Type}, {\"diag_1\", type text}, {\"diag_2\", type text}, {\"diag_3\", type text}, {\"number_diagnoses\", Int64.Type}, {\"max_glu_serum\", type text}, {\"A1Cresult\", type text}, {\"metformin\", type text}, {\"repaglinide\", type text}, {\"nateglinide\", type text}, {\"chlorpropamide\", type text}, {\"glimepiride\", type text}, {\"acetohexamide\", type text}, {\"glipizide\", type text}, {\"glyburide\", type text}, {\"tolbutamide\", type text}, {\"pioglitazone\", type text}, {\"rosiglitazone\", type text}, {\"acarbose\", type text}, {\"miglitol\", type text}, {\"troglitazone\", type text}, {\"tolazamide\", type text}, {\"examide\", type text}, {\"citoglipton\", type text}, {\"insulin\", type text}, {\"glyburide-metformin\", type text}, {\"glipizide-metformin\", type text}, {\"glimepiride-pioglitazone\", type text}, {\"metformin-rosiglitazone\", type text}, {\"metformin-pioglitazone\", type text}, {\"change\", type text}, {\"diabetesMed\", type text}, {\"readmitted\", type text}}),",
          "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"weight\", \"payer_code\"}),",
          "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Colunas Removidas\",{{\"encounter_id\", \"ID_do_encontro\"}, {\"patient_nbr\", \"paciente_nbr\"}, {\"race\", \"raca\"}, {\"gender\", \"genero\"}, {\"age\", \"idade\"}, {\"admission_type_id\", \"ID_tipo_de_admissao\"}, {\"discharge_disposition_id\", \"ID_disposição_de_alta\"}, {\"admission_source_id\", \"ID_fonte_de_admissao\"}, {\"time_in_hospital\", \"Dias_de_Internação\"}, {\"medical_specialty\", \"especialidade_medica\"}, {\"num_lab_procedures\", \"Qtd_Exames_Laboratoriais\"}, {\"num_procedures\", \"Qtd_Outros_Procedimentos\"}, {\"num_medications\", \"Qtd_Medicamentos\"}, {\"number_outpatient\", \"Consultas_Ambulatoriais_Anterior\"}, {\"number_emergency\", \"Visitas_Pronto_Socorro\"}, {\"number_inpatient\", \"Internacoes_Anteriores\"}, {\"diag_1\", \"Diagnostico_Primario\"}, {\"diag_2\", \"Diagnostico_Segudario\"}, {\"diag_3\", \"Diagnostico_Terciario\"}, {\"number_diagnoses\", \"Total_Diagnosticos\"}, {\"max_glu_serum\", \"Teste_de_Glicemia\"}, {\"A1Cresult\", \"Exame_HbA1c\"}, {\"metformin\", \"Metformina\"}, {\"repaglinide\", \"Alteracao_na_Medicacao\"}, {\"nateglinide\", \"Nateglinida\"}, {\"chlorpropamide\", \"Clorpropamida\"}, {\"glimepiride\", \"Glimepirida\"}, {\"acetohexamide\", \"Acetohexamide\"}, {\"glipizide\", \"Glipizida\"}, {\"glyburide\", \"Gliburida\"}, {\"tolbutamide\", \"Tolbutamida\"}, {\"pioglitazone\", \"Pioglitazona\"}, {\"rosiglitazone\", \"Rosiglitazone\"}, {\"acarbose\", \"Acarbose\"}, {\"miglitol\", \"Miglitol\"}, {\"troglitazone\", \"Troglitazona\"}, {\"tolazamide\", \"Tolazamida\"}, {\"examide\", \"Examida\"}, {\"citoglipton\", \"Sitagliptin\"}, {\"insulin\", \"Insulina\"}, {\"glyburide-metformin\", \"Gliburida-Metformina\"}, {\"glipizide-metformin\", \"Glipizida-Metformina\"}, {\"glimepiride-pioglitazone\", \"Metformina-Rosiglitazona\"}}),",
          "    #\"Colunas Removidas1\" = Table.RemoveColumns(#\"Colunas Renomeadas\",{\"metformin-rosiglitazone\"}),",
          "    #\"Colunas Renomeadas1\" = Table.RenameColumns(#\"Colunas Removidas1\",{{\"change\", \"Mudou_medicamento\"}, {\"diabetesMed\", \"Prescricao_de_Medicamento\"}, {\"readmitted\", \"Readmissao\"}, {\"paciente_nbr\", \"Paciente_Nbr\"}, {\"raca\", \"Raca\"}, {\"genero\", \"Genero\"}, {\"idade\", \"Idade\"}, {\"metformin-pioglitazone\", \"Metformina_pioglitazona\"}}),",
          "    #\"Coluna Condicional Adicionada\" = Table.AddColumn(#\"Colunas Renomeadas1\", \"Readmissao_30d\", each if [Readmissao] = \"<30\" then 1 else 0),",
          "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Coluna Condicional Adicionada\",{{\"Readmissao_30d\", Int64.Type}}),",
          "    #\"Colunas Renomeadas2\" = Table.RenameColumns(#\"Tipo Alterado1\",{{\"Diagnostico_Segudario\", \"Diagnostico_Secundario\"}}),",
          "    #\"Personalização Adicionada\" = Table.AddColumn(#\"Colunas Renomeadas2\", \"Risco_DRC\", each if Text.StartsWith([Diagnostico_Primario], \"585\") or",
          "   Text.StartsWith([Diagnostico_Primario], \"403\") or",
          "   Text.StartsWith([Diagnostico_Primario], \"250.4\") or",
          "   Text.StartsWith([Diagnostico_Secundario], \"585\") or",
          "   Text.StartsWith([Diagnostico_Secundario], \"403\") or",
          "   Text.StartsWith([Diagnostico_Secundario], \"250.4\") or",
          "   Text.StartsWith([Diagnostico_Terciario], \"585\") or",
          "   Text.StartsWith([Diagnostico_Terciario], \"403\") or",
          "   Text.StartsWith([Diagnostico_Terciario], \"250.4\")",
          "then 1 else 0),",
          "    #\"Tipo Alterado2\" = Table.TransformColumnTypes(#\"Personalização Adicionada\",{{\"Risco_DRC\", Int64.Type}}),",
          "    #\"Índice Adicionado\" = Table.AddIndexColumn(#\"Tipo Alterado2\", \"Índice\", 1, 1, Int64.Type),",
          "    #\"Personalização Adicionada1\" = Table.AddColumn(#\"Índice Adicionado\", \"Ano\", each 1999 + Number.IntegerDivide([Índice] - 1, Number.IntegerDivide(101766, 10))),",
          "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Personalização Adicionada1\", each true),",
          "    #\"Tipo Alterado3\" = Table.TransformColumnTypes(#\"Linhas Filtradas\",{{\"Ano\", Int64.Type}}),",
          "    #\"Valor Substituído\" = Table.ReplaceValue(#\"Tipo Alterado3\",2009,2008,Replacer.ReplaceValue,{\"Ano\"}),",
          "    #\"Tipo Alterado4\" = Table.TransformColumnTypes(#\"Valor Substituído\",{{\"Ano\", Int64.Type}}),",
          "    #\"Linhas Filtradas1\" = Table.SelectRows(#\"Tipo Alterado4\", each true),",
          "    #\"Colunas Removidas2\" = Table.RemoveColumns(#\"Linhas Filtradas1\",{\"Índice\"}),",
          "    #\"Colunas Renomeadas3\" = Table.RenameColumns(#\"Colunas Removidas2\",{{\"especialidade_medica\", \"Especialidade_medica\"}, {\"Alteracao_na_Medicacao\", \"Repaglinida\"}, {\"Acetohexamide\", \"Acetohexamida\"}, {\"Rosiglitazone\", \"Rosiglitazona\"}})",
          "in",
          "    #\"Colunas Renomeadas3\""
        ],
        "kind": "m",
        "lineageTag": "dea67636-5568-4ddf-bed8-687a79c2e3ec"
      }
    ],
    "relationships": [
      {
        "name": "b72aa6fe-9f39-b2ac-2883-cf47dd2fa247",
        "fromColumn": "ID_do_encontro",
        "fromTable": "Fato_Intenacao",
        "toColumn": "ID_do_encontro",
        "toTable": "Dim_Paciente"
      },
      {
        "name": "9a166df0-4748-5918-e4eb-b310af2235cc",
        "fromColumn": "ID_do_encontro",
        "fromTable": "Fato_Intenacao",
        "toColumn": "ID_do_encontro",
        "toTable": "Dim_Clinico"
      },
      {
        "name": "68bf3a6b-3ea7-1127-fd3e-12b86dbf5acc",
        "fromColumn": "ID_do_encontro",
        "fromTable": "Fato_Intenacao",
        "toColumn": "ID_do_encontro",
        "toTable": "Dim_Tratamento"
      },
      {
        "name": "dec45f66-e945-0fde-a5f6-8c9220aa2b05",
        "fromColumn": "ID_do_encontro",
        "fromTable": "Fato_Intenacao",
        "toColumn": "ID_do_encontro",
        "toTable": "Dim_Admissao"
      },
      {
        "name": "a925b9cd-b699-3546-9677-e4cf16c28d4d",
        "fromColumn": "data_completa",
        "fromTable": "Fato_Intenacao",
        "toColumn": "Date",
        "toTable": "Dim_Calendario"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "Dim_Paciente",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_do_encontro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bd674458-f2f6-4d4e-830b-860cd86c7b9a",
            "sourceColumn": "ID_do_encontro",
            "summarizeBy": "none"
          },
          {
            "name": "SK_paciente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6cc6b5df-b96e-41e4-b629-7b342aa7e7a5",
            "sourceColumn": "SK_paciente",
            "summarizeBy": "none"
          },
          {
            "name": "Paciente_Nbr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "72b24eb8-6296-4838-b4d8-380a9a743472",
            "sourceColumn": "Paciente_Nbr",
            "summarizeBy": "none"
          },
          {
            "name": "Raca",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "4088ae6f-cb4a-4f55-b760-b49d04c66c09",
            "sourceColumn": "Raca",
            "summarizeBy": "none"
          },
          {
            "name": "Genero",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "8e687dd8-5905-4e79-b6a4-badad0b27320",
            "sourceColumn": "Genero",
            "summarizeBy": "none"
          },
          {
            "name": "Idade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "0312e08d-e0bd-44c1-8f4f-8ff5c7fac2b9",
            "sourceColumn": "Idade",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "32d3048c-7561-416d-911e-8b781d393426",
        "partitions": [
          {
            "name": "Dim_Paciente",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\geova\\OneDrive - UniCEUB\\Projeto_Final_BI_II\\dados\\diabetic_data.csv\"),[Delimiter=\",\", Columns=50, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"encounter_id\", Int64.Type}, {\"patient_nbr\", Int64.Type}, {\"race\", type text}, {\"gender\", type text}, {\"age\", type text}, {\"weight\", type text}, {\"admission_type_id\", Int64.Type}, {\"discharge_disposition_id\", Int64.Type}, {\"admission_source_id\", Int64.Type}, {\"time_in_hospital\", Int64.Type}, {\"payer_code\", type text}, {\"medical_specialty\", type text}, {\"num_lab_procedures\", Int64.Type}, {\"num_procedures\", Int64.Type}, {\"num_medications\", Int64.Type}, {\"number_outpatient\", Int64.Type}, {\"number_emergency\", Int64.Type}, {\"number_inpatient\", Int64.Type}, {\"diag_1\", type text}, {\"diag_2\", type text}, {\"diag_3\", type text}, {\"number_diagnoses\", Int64.Type}, {\"max_glu_serum\", type text}, {\"A1Cresult\", type text}, {\"metformin\", type text}, {\"repaglinide\", type text}, {\"nateglinide\", type text}, {\"chlorpropamide\", type text}, {\"glimepiride\", type text}, {\"acetohexamide\", type text}, {\"glipizide\", type text}, {\"glyburide\", type text}, {\"tolbutamide\", type text}, {\"pioglitazone\", type text}, {\"rosiglitazone\", type text}, {\"acarbose\", type text}, {\"miglitol\", type text}, {\"troglitazone\", type text}, {\"tolazamide\", type text}, {\"examide\", type text}, {\"citoglipton\", type text}, {\"insulin\", type text}, {\"glyburide-metformin\", type text}, {\"glipizide-metformin\", type text}, {\"glimepiride-pioglitazone\", type text}, {\"metformin-rosiglitazone\", type text}, {\"metformin-pioglitazone\", type text}, {\"change\", type text}, {\"diabetesMed\", type text}, {\"readmitted\", type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"weight\", \"payer_code\"}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Colunas Removidas\",{{\"encounter_id\", \"ID_do_encontro\"}, {\"patient_nbr\", \"paciente_nbr\"}, {\"race\", \"raca\"}, {\"gender\", \"genero\"}, {\"age\", \"idade\"}, {\"admission_type_id\", \"ID_tipo_de_admissao\"}, {\"discharge_disposition_id\", \"ID_disposição_de_alta\"}, {\"admission_source_id\", \"ID_fonte_de_admissao\"}, {\"time_in_hospital\", \"Dias_de_Internação\"}, {\"medical_specialty\", \"especialidade_medica\"}, {\"num_lab_procedures\", \"Qtd_Exames_Laboratoriais\"}, {\"num_procedures\", \"Qtd_Outros_Procedimentos\"}, {\"num_medications\", \"Qtd_Medicamentos\"}, {\"number_outpatient\", \"Consultas_Ambulatoriais_Anterior\"}, {\"number_emergency\", \"Visitas_Pronto_Socorro\"}, {\"number_inpatient\", \"Internacoes_Anteriores\"}, {\"diag_1\", \"Diagnostico_Primario\"}, {\"diag_2\", \"Diagnostico_Segudario\"}, {\"diag_3\", \"Diagnostico_Terciario\"}, {\"number_diagnoses\", \"Total_Diagnosticos\"}, {\"max_glu_serum\", \"Teste_de_Glicemia\"}, {\"A1Cresult\", \"Exame_HbA1c\"}, {\"metformin\", \"Metformina\"}, {\"repaglinide\", \"Alteracao_na_Medicacao\"}, {\"nateglinide\", \"Nateglinida\"}, {\"chlorpropamide\", \"Clorpropamida\"}, {\"glimepiride\", \"Glimepirida\"}, {\"acetohexamide\", \"Acetohexamide\"}, {\"glipizide\", \"Glipizida\"}, {\"glyburide\", \"Gliburida\"}, {\"tolbutamide\", \"Tolbutamida\"}, {\"pioglitazone\", \"Pioglitazona\"}, {\"rosiglitazone\", \"Rosiglitazone\"}, {\"acarbose\", \"Acarbose\"}, {\"miglitol\", \"Miglitol\"}, {\"troglitazone\", \"Troglitazona\"}, {\"tolazamide\", \"Tolazamida\"}, {\"examide\", \"Examida\"}, {\"citoglipton\", \"Sitagliptin\"}, {\"insulin\", \"Insulina\"}, {\"glyburide-metformin\", \"Gliburida-Metformina\"}, {\"glipizide-metformin\", \"Glipizida-Metformina\"}, {\"glimepiride-pioglitazone\", \"Metformina-Rosiglitazona\"}}),",
                "    #\"Colunas Removidas1\" = Table.RemoveColumns(#\"Colunas Renomeadas\",{\"metformin-rosiglitazone\"}),",
                "    #\"Colunas Renomeadas1\" = Table.RenameColumns(#\"Colunas Removidas1\",{{\"change\", \"Mudou_medicamento\"}, {\"diabetesMed\", \"Prescricao_de_Medicamento\"}, {\"readmitted\", \"Readmissao\"}, {\"paciente_nbr\", \"Paciente_Nbr\"}, {\"raca\", \"Raca\"}, {\"genero\", \"Genero\"}, {\"idade\", \"Idade\"}, {\"metformin-pioglitazone\", \"Metformina_pioglitazona\"}}),",
                "    #\"Coluna Condicional Adicionada\" = Table.AddColumn(#\"Colunas Renomeadas1\", \"Readmissao_30d\", each if [Readmissao] = \"<30\" then 1 else 0),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Coluna Condicional Adicionada\",{{\"Readmissao_30d\", Int64.Type}}),",
                "    #\"Colunas Renomeadas2\" = Table.RenameColumns(#\"Tipo Alterado1\",{{\"Diagnostico_Segudario\", \"Diagnostico_Secundario\"}}),",
                "    #\"Personalização Adicionada\" = Table.AddColumn(#\"Colunas Renomeadas2\", \"Risco_DRC\", each if Text.StartsWith([Diagnostico_Primario], \"585\") or",
                "   Text.StartsWith([Diagnostico_Primario], \"403\") or",
                "   Text.StartsWith([Diagnostico_Primario], \"250.4\") or",
                "   Text.StartsWith([Diagnostico_Secundario], \"585\") or",
                "   Text.StartsWith([Diagnostico_Secundario], \"403\") or",
                "   Text.StartsWith([Diagnostico_Secundario], \"250.4\") or",
                "   Text.StartsWith([Diagnostico_Terciario], \"585\") or",
                "   Text.StartsWith([Diagnostico_Terciario], \"403\") or",
                "   Text.StartsWith([Diagnostico_Terciario], \"250.4\")",
                "then 1 else 0),",
                "    #\"Tipo Alterado2\" = Table.TransformColumnTypes(#\"Personalização Adicionada\",{{\"Risco_DRC\", Int64.Type}}),",
                "    #\"Índice Adicionado\" = Table.AddIndexColumn(#\"Tipo Alterado2\", \"Índice\", 1, 1, Int64.Type),",
                "    #\"Personalização Adicionada1\" = Table.AddColumn(#\"Índice Adicionado\", \"Ano\", each 1999 + Number.IntegerDivide([Índice] - 1, Number.IntegerDivide(101766, 10))),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Personalização Adicionada1\", each true),",
                "    #\"Tipo Alterado3\" = Table.TransformColumnTypes(#\"Linhas Filtradas\",{{\"Ano\", Int64.Type}}),",
                "    #\"Valor Substituído\" = Table.ReplaceValue(#\"Tipo Alterado3\",2009,2008,Replacer.ReplaceValue,{\"Ano\"}),",
                "    #\"Tipo Alterado4\" = Table.TransformColumnTypes(#\"Valor Substituído\",{{\"Ano\", Int64.Type}}),",
                "    #\"Linhas Filtradas1\" = Table.SelectRows(#\"Tipo Alterado4\", each true),",
                "    #\"Colunas Removidas2\" = Table.RemoveColumns(#\"Linhas Filtradas1\",{\"Índice\", \"ID_tipo_de_admissao\", \"ID_disposição_de_alta\", \"ID_fonte_de_admissao\", \"Dias_de_Internação\", \"especialidade_medica\", \"Qtd_Exames_Laboratoriais\", \"Qtd_Outros_Procedimentos\", \"Qtd_Medicamentos\", \"Consultas_Ambulatoriais_Anterior\", \"Visitas_Pronto_Socorro\", \"Internacoes_Anteriores\", \"Diagnostico_Primario\", \"Diagnostico_Secundario\", \"Diagnostico_Terciario\", \"Total_Diagnosticos\", \"Teste_de_Glicemia\", \"Exame_HbA1c\", \"Metformina\", \"Alteracao_na_Medicacao\", \"Nateglinida\", \"Clorpropamida\", \"Glimepirida\", \"Acetohexamide\", \"Glipizida\", \"Gliburida\", \"Tolbutamida\", \"Pioglitazona\", \"Rosiglitazone\", \"Acarbose\", \"Miglitol\", \"Troglitazona\", \"Tolazamida\", \"Examida\", \"Sitagliptin\", \"Insulina\", \"Gliburida-Metformina\", \"Glipizida-Metformina\", \"Metformina-Rosiglitazona\", \"Metformina_pioglitazona\", \"Mudou_medicamento\", \"Prescricao_de_Medicamento\", \"Readmissao\", \"Readmissao_30d\", \"Risco_DRC\", \"Ano\"}),",
                "    #\"Índice Adicionado1\" = Table.AddIndexColumn(#\"Colunas Removidas2\", \"Índice\", 1, 1, Int64.Type),",
                "    #\"Colunas Renomeadas3\" = Table.RenameColumns(#\"Índice Adicionado1\",{{\"Índice\", \"SK_paciente\"}}),",
                "    #\"Colunas Reordenadas\" = Table.ReorderColumns(#\"Colunas Renomeadas3\",{\"SK_paciente\", \"ID_do_encontro\", \"Paciente_Nbr\", \"Raca\", \"Genero\", \"Idade\"}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Colunas Reordenadas\",\"Male\",\"Masculino\",Replacer.ReplaceText,{\"Genero\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"Female\",\"Feminino\",Replacer.ReplaceText,{\"Genero\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\"Caucasian\",\"Caucasiano\",Replacer.ReplaceText,{\"Raca\"}),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",\"AfricanAmerican\",\"Afro-Americano\",Replacer.ReplaceText,{\"Raca\"}),",
                "    #\"Replaced Value4\" = Table.ReplaceValue(#\"Replaced Value3\",\"Hispanic\",\"Hispânico\",Replacer.ReplaceText,{\"Raca\"}),",
                "    #\"Replaced Value5\" = Table.ReplaceValue(#\"Replaced Value4\",\"Asian\",\"Asiático\",Replacer.ReplaceText,{\"Raca\"}),",
                "    #\"Replaced Value6\" = Table.ReplaceValue(#\"Replaced Value5\",\"Other\",\"Outro\",Replacer.ReplaceText,{\"Raca\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Replaced Value6\", each true),",
                "    #\"Replaced Value7\" = Table.ReplaceValue(#\"Filtered Rows\",\"?\",\"Não informado\",Replacer.ReplaceText,{\"Raca\"})",
                "in",
                "    #\"Replaced Value7\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim_Admissao",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_do_encontro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "877e57b3-3d5a-47c6-9e4d-02cf98048753",
            "sourceColumn": "ID_do_encontro",
            "summarizeBy": "none"
          },
          {
            "name": "ID_disposição_de_alta",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f0e6ce2f-961a-45d7-b8b2-d1a1610bfc2d",
            "sourceColumn": "ID_disposição_de_alta",
            "summarizeBy": "none"
          },
          {
            "name": "ID_fonte_de_admissao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "de496e63-4cd5-49b5-b0fe-1d5ff436dff9",
            "sourceColumn": "ID_fonte_de_admissao",
            "summarizeBy": "none"
          },
          {
            "name": "ID_tipo_de_admissao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e5695ec7-b12c-4003-92bd-6a7e5f6e4318",
            "sourceColumn": "ID_tipo_de_admissao",
            "summarizeBy": "none"
          },
          {
            "name": "SK_Admissao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6deb5eca-4538-4522-83f0-340237eb1c34",
            "sourceColumn": "SK_Admissao",
            "summarizeBy": "none"
          },
          {
            "name": "Tipo_admissao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a43489e2-d70c-4306-8c40-1f8cc1ffdbe3",
            "sourceColumn": "Tipo_admissao",
            "summarizeBy": "none"
          },
          {
            "name": "Origem_admissao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c95fafed-1b1a-42e2-885a-a70aa0093196",
            "sourceColumn": "Origem_admissao",
            "summarizeBy": "none"
          },
          {
            "name": "Destino_alta",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9245d032-3b29-4f31-a743-4d3709b2e074",
            "sourceColumn": "Destino_alta",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "572c6895-0c54-4bc1-ac8a-c243de3ccd07",
        "partitions": [
          {
            "name": "Dim_Admissao",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\geova\\OneDrive - UniCEUB\\Projeto_Final_BI_II\\dados\\diabetic_data.csv\"),[Delimiter=\",\", Columns=50, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"encounter_id\", Int64.Type}, {\"patient_nbr\", Int64.Type}, {\"race\", type text}, {\"gender\", type text}, {\"age\", type text}, {\"weight\", type text}, {\"admission_type_id\", Int64.Type}, {\"discharge_disposition_id\", Int64.Type}, {\"admission_source_id\", Int64.Type}, {\"time_in_hospital\", Int64.Type}, {\"payer_code\", type text}, {\"medical_specialty\", type text}, {\"num_lab_procedures\", Int64.Type}, {\"num_procedures\", Int64.Type}, {\"num_medications\", Int64.Type}, {\"number_outpatient\", Int64.Type}, {\"number_emergency\", Int64.Type}, {\"number_inpatient\", Int64.Type}, {\"diag_1\", type text}, {\"diag_2\", type text}, {\"diag_3\", type text}, {\"number_diagnoses\", Int64.Type}, {\"max_glu_serum\", type text}, {\"A1Cresult\", type text}, {\"metformin\", type text}, {\"repaglinide\", type text}, {\"nateglinide\", type text}, {\"chlorpropamide\", type text}, {\"glimepiride\", type text}, {\"acetohexamide\", type text}, {\"glipizide\", type text}, {\"glyburide\", type text}, {\"tolbutamide\", type text}, {\"pioglitazone\", type text}, {\"rosiglitazone\", type text}, {\"acarbose\", type text}, {\"miglitol\", type text}, {\"troglitazone\", type text}, {\"tolazamide\", type text}, {\"examide\", type text}, {\"citoglipton\", type text}, {\"insulin\", type text}, {\"glyburide-metformin\", type text}, {\"glipizide-metformin\", type text}, {\"glimepiride-pioglitazone\", type text}, {\"metformin-rosiglitazone\", type text}, {\"metformin-pioglitazone\", type text}, {\"change\", type text}, {\"diabetesMed\", type text}, {\"readmitted\", type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"weight\", \"payer_code\"}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Colunas Removidas\",{{\"encounter_id\", \"ID_do_encontro\"}, {\"patient_nbr\", \"paciente_nbr\"}, {\"race\", \"raca\"}, {\"gender\", \"genero\"}, {\"age\", \"idade\"}, {\"admission_type_id\", \"ID_tipo_de_admissao\"}, {\"discharge_disposition_id\", \"ID_disposição_de_alta\"}, {\"admission_source_id\", \"ID_fonte_de_admissao\"}, {\"time_in_hospital\", \"Dias_de_Internação\"}, {\"medical_specialty\", \"especialidade_medica\"}, {\"num_lab_procedures\", \"Qtd_Exames_Laboratoriais\"}, {\"num_procedures\", \"Qtd_Outros_Procedimentos\"}, {\"num_medications\", \"Qtd_Medicamentos\"}, {\"number_outpatient\", \"Consultas_Ambulatoriais_Anterior\"}, {\"number_emergency\", \"Visitas_Pronto_Socorro\"}, {\"number_inpatient\", \"Internacoes_Anteriores\"}, {\"diag_1\", \"Diagnostico_Primario\"}, {\"diag_2\", \"Diagnostico_Segudario\"}, {\"diag_3\", \"Diagnostico_Terciario\"}, {\"number_diagnoses\", \"Total_Diagnosticos\"}, {\"max_glu_serum\", \"Teste_de_Glicemia\"}, {\"A1Cresult\", \"Exame_HbA1c\"}, {\"metformin\", \"Metformina\"}, {\"repaglinide\", \"Alteracao_na_Medicacao\"}, {\"nateglinide\", \"Nateglinida\"}, {\"chlorpropamide\", \"Clorpropamida\"}, {\"glimepiride\", \"Glimepirida\"}, {\"acetohexamide\", \"Acetohexamide\"}, {\"glipizide\", \"Glipizida\"}, {\"glyburide\", \"Gliburida\"}, {\"tolbutamide\", \"Tolbutamida\"}, {\"pioglitazone\", \"Pioglitazona\"}, {\"rosiglitazone\", \"Rosiglitazone\"}, {\"acarbose\", \"Acarbose\"}, {\"miglitol\", \"Miglitol\"}, {\"troglitazone\", \"Troglitazona\"}, {\"tolazamide\", \"Tolazamida\"}, {\"examide\", \"Examida\"}, {\"citoglipton\", \"Sitagliptin\"}, {\"insulin\", \"Insulina\"}, {\"glyburide-metformin\", \"Gliburida-Metformina\"}, {\"glipizide-metformin\", \"Glipizida-Metformina\"}, {\"glimepiride-pioglitazone\", \"Metformina-Rosiglitazona\"}}),",
                "    #\"Colunas Removidas1\" = Table.RemoveColumns(#\"Colunas Renomeadas\",{\"metformin-rosiglitazone\"}),",
                "    #\"Colunas Renomeadas1\" = Table.RenameColumns(#\"Colunas Removidas1\",{{\"change\", \"Mudou_medicamento\"}, {\"diabetesMed\", \"Prescricao_de_Medicamento\"}, {\"readmitted\", \"Readmissao\"}, {\"paciente_nbr\", \"Paciente_Nbr\"}, {\"raca\", \"Raca\"}, {\"genero\", \"Genero\"}, {\"idade\", \"Idade\"}, {\"metformin-pioglitazone\", \"Metformina_pioglitazona\"}}),",
                "    #\"Coluna Condicional Adicionada\" = Table.AddColumn(#\"Colunas Renomeadas1\", \"Readmissao_30d\", each if [Readmissao] = \"<30\" then 1 else 0),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Coluna Condicional Adicionada\",{{\"Readmissao_30d\", Int64.Type}}),",
                "    #\"Colunas Renomeadas2\" = Table.RenameColumns(#\"Tipo Alterado1\",{{\"Diagnostico_Segudario\", \"Diagnostico_Secundario\"}}),",
                "    #\"Personalização Adicionada\" = Table.AddColumn(#\"Colunas Renomeadas2\", \"Risco_DRC\", each if Text.StartsWith([Diagnostico_Primario], \"585\") or",
                "   Text.StartsWith([Diagnostico_Primario], \"403\") or",
                "   Text.StartsWith([Diagnostico_Primario], \"250.4\") or",
                "   Text.StartsWith([Diagnostico_Secundario], \"585\") or",
                "   Text.StartsWith([Diagnostico_Secundario], \"403\") or",
                "   Text.StartsWith([Diagnostico_Secundario], \"250.4\") or",
                "   Text.StartsWith([Diagnostico_Terciario], \"585\") or",
                "   Text.StartsWith([Diagnostico_Terciario], \"403\") or",
                "   Text.StartsWith([Diagnostico_Terciario], \"250.4\")",
                "then 1 else 0),",
                "    #\"Tipo Alterado2\" = Table.TransformColumnTypes(#\"Personalização Adicionada\",{{\"Risco_DRC\", Int64.Type}}),",
                "    #\"Índice Adicionado\" = Table.AddIndexColumn(#\"Tipo Alterado2\", \"Índice\", 1, 1, Int64.Type),",
                "    #\"Personalização Adicionada1\" = Table.AddColumn(#\"Índice Adicionado\", \"Ano\", each 1999 + Number.IntegerDivide([Índice] - 1, Number.IntegerDivide(101766, 10))),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Personalização Adicionada1\", each true),",
                "    #\"Tipo Alterado3\" = Table.TransformColumnTypes(#\"Linhas Filtradas\",{{\"Ano\", Int64.Type}}),",
                "    #\"Valor Substituído\" = Table.ReplaceValue(#\"Tipo Alterado3\",2009,2008,Replacer.ReplaceValue,{\"Ano\"}),",
                "    #\"Tipo Alterado4\" = Table.TransformColumnTypes(#\"Valor Substituído\",{{\"Ano\", Int64.Type}}),",
                "    #\"Linhas Filtradas1\" = Table.SelectRows(#\"Tipo Alterado4\", each true),",
                "    #\"Colunas Removidas2\" = Table.RemoveColumns(#\"Linhas Filtradas1\",{\"Índice\"}),",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(#\"Colunas Removidas2\",{\"ID_do_encontro\", \"ID_disposição_de_alta\", \"ID_fonte_de_admissao\", \"ID_tipo_de_admissao\"}),",
                "    #\"Índice Adicionado1\" = Table.AddIndexColumn(#\"Outras Colunas Removidas\", \"Índice\", 1, 1, Int64.Type),",
                "    #\"Colunas Renomeadas3\" = Table.RenameColumns(#\"Índice Adicionado1\",{{\"Índice\", \"SK_Admissao\"}}),",
                "    #\"Colunas Reordenadas\" = Table.ReorderColumns(#\"Colunas Renomeadas3\",{\"SK_Admissao\", \"ID_do_encontro\", \"ID_disposição_de_alta\", \"ID_fonte_de_admissao\", \"ID_tipo_de_admissao\"}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Colunas Reordenadas\", \"Tipo_admissao\", each if [ID_tipo_de_admissao] = 1 then \"Emergência\" else if [ID_tipo_de_admissao] = 2 then \"Urgente\" else if [ID_tipo_de_admissao] = 3 then \"Eletiva\" else if [ID_tipo_de_admissao] = 4 then \"Recém-nascido\" else if [ID_tipo_de_admissao] = 5 then \"Não disponível\" else if [ID_tipo_de_admissao] = 6 then \"Não informado\" else if [ID_tipo_de_admissao] = 7 then \"Centro de Trauma\" else if [ID_tipo_de_admissao] = 8 then \"Não mapeado\" else \"Não informado\"),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Added Conditional Column\", \"Destino_alta\", each if List.Contains({1}, [ID_disposição_de_alta]) then \"Alta para casa\"",
                "else if List.Contains({6,8}, [ID_disposição_de_alta]) then \"Alta com cuidados domiciliares\"",
                "else if List.Contains({2,3,4,5,9,10,15,22,23,24,27,28,29,30}, [ID_disposição_de_alta]) then \"Transferência para outra instituição\"",
                "else if List.Contains({7}, [ID_disposição_de_alta]) then \"Saída sem alta médica\"",
                "else if List.Contains({11,19,20,21}, [ID_disposição_de_alta]) then \"Óbito\"",
                "else if List.Contains({13,14}, [ID_disposição_de_alta]) then \"Cuidados paliativos (Hospice)\"",
                "else if List.Contains({12}, [ID_disposição_de_alta]) then \"Permanece internado / retorno ambulatorial\"",
                "else if List.Contains({16,17}, [ID_disposição_de_alta]) then \"Referência para atendimento ambulatorial\"",
                "else \"Não informado\"),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Added Custom\", \"Origem_admissao\", each if List.Contains({1,2,3}, [ID_fonte_de_admissao]) then \"Encaminhamento médico\"",
                "else if List.Contains({4,5,6,10,18,22,25,26}, [ID_fonte_de_admissao]) then \"Transferência de outra instituição\"",
                "else if List.Contains({7}, [ID_fonte_de_admissao]) then \"Pronto-socorro / Emergência\"",
                "else if List.Contains({8}, [ID_fonte_de_admissao]) then \"Encaminhamento judicial\"",
                "else if List.Contains({11,12,13,14,23,24}, [ID_fonte_de_admissao]) then \"Nascimento\"",
                "else if List.Contains({19}, [ID_fonte_de_admissao]) then \"Readmissão home health\"",
                "else \"Não informado\"),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Added Custom1\",{\"SK_Admissao\", \"ID_do_encontro\", \"ID_disposição_de_alta\", \"ID_fonte_de_admissao\", \"ID_tipo_de_admissao\", \"Tipo_admissao\", \"Origem_admissao\", \"Destino_alta\"})",
                "in",
                "    #\"Reordered Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim_Clinico",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_do_encontro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6661fe12-5775-4910-968b-64b2a3060636",
            "sourceColumn": "ID_do_encontro",
            "summarizeBy": "none"
          },
          {
            "name": "Diagnostico_Primario",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "53e4aba9-2b86-4afd-b357-e49bd1aa3992",
            "sourceColumn": "Diagnostico_Primario",
            "summarizeBy": "none"
          },
          {
            "name": "Diagnostico_Secundario",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "86da16e1-0551-401b-85a6-8f13f4090c49",
            "sourceColumn": "Diagnostico_Secundario",
            "summarizeBy": "none"
          },
          {
            "name": "Diagnostico_Terciario",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "9059022c-9c41-4bc8-9110-d24c19818ab8",
            "sourceColumn": "Diagnostico_Terciario",
            "summarizeBy": "none"
          },
          {
            "name": "Teste_de_Glicemia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "67dc59bf-78ef-4b31-9190-8b7ec56e60f9",
            "sourceColumn": "Teste_de_Glicemia",
            "summarizeBy": "none"
          },
          {
            "name": "Exame_HbA1c",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "f0430b0b-688c-4b15-8f09-ea3353969eb6",
            "sourceColumn": "Exame_HbA1c",
            "summarizeBy": "none"
          },
          {
            "name": "Especialidade_medica",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "fcacd32b-bc1d-454f-9f4f-936e4d45e816",
            "sourceColumn": "Especialidade_medica",
            "summarizeBy": "none"
          },
          {
            "name": "Risco_DRC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f3e62c73-2d50-4c8e-9c3d-50cab0f3c113",
            "sourceColumn": "Risco_DRC",
            "summarizeBy": "none"
          },
          {
            "name": "SK_Clinico",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "aba09bd0-1c1d-4383-a1ea-a5449699df0f",
            "sourceColumn": "SK_Clinico",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5736f072-d636-43d0-b12e-00187581c512",
        "partitions": [
          {
            "name": "Dim_Clinico",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\geova\\OneDrive - UniCEUB\\Projeto_Final_BI_II\\dados\\diabetic_data.csv\"),[Delimiter=\",\", Columns=50, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"encounter_id\", Int64.Type}, {\"patient_nbr\", Int64.Type}, {\"race\", type text}, {\"gender\", type text}, {\"age\", type text}, {\"weight\", type text}, {\"admission_type_id\", Int64.Type}, {\"discharge_disposition_id\", Int64.Type}, {\"admission_source_id\", Int64.Type}, {\"time_in_hospital\", Int64.Type}, {\"payer_code\", type text}, {\"medical_specialty\", type text}, {\"num_lab_procedures\", Int64.Type}, {\"num_procedures\", Int64.Type}, {\"num_medications\", Int64.Type}, {\"number_outpatient\", Int64.Type}, {\"number_emergency\", Int64.Type}, {\"number_inpatient\", Int64.Type}, {\"diag_1\", type text}, {\"diag_2\", type text}, {\"diag_3\", type text}, {\"number_diagnoses\", Int64.Type}, {\"max_glu_serum\", type text}, {\"A1Cresult\", type text}, {\"metformin\", type text}, {\"repaglinide\", type text}, {\"nateglinide\", type text}, {\"chlorpropamide\", type text}, {\"glimepiride\", type text}, {\"acetohexamide\", type text}, {\"glipizide\", type text}, {\"glyburide\", type text}, {\"tolbutamide\", type text}, {\"pioglitazone\", type text}, {\"rosiglitazone\", type text}, {\"acarbose\", type text}, {\"miglitol\", type text}, {\"troglitazone\", type text}, {\"tolazamide\", type text}, {\"examide\", type text}, {\"citoglipton\", type text}, {\"insulin\", type text}, {\"glyburide-metformin\", type text}, {\"glipizide-metformin\", type text}, {\"glimepiride-pioglitazone\", type text}, {\"metformin-rosiglitazone\", type text}, {\"metformin-pioglitazone\", type text}, {\"change\", type text}, {\"diabetesMed\", type text}, {\"readmitted\", type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"weight\", \"payer_code\"}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Colunas Removidas\",{{\"encounter_id\", \"ID_do_encontro\"}, {\"patient_nbr\", \"paciente_nbr\"}, {\"race\", \"raca\"}, {\"gender\", \"genero\"}, {\"age\", \"idade\"}, {\"admission_type_id\", \"ID_tipo_de_admissao\"}, {\"discharge_disposition_id\", \"ID_disposição_de_alta\"}, {\"admission_source_id\", \"ID_fonte_de_admissao\"}, {\"time_in_hospital\", \"Dias_de_Internação\"}, {\"medical_specialty\", \"especialidade_medica\"}, {\"num_lab_procedures\", \"Qtd_Exames_Laboratoriais\"}, {\"num_procedures\", \"Qtd_Outros_Procedimentos\"}, {\"num_medications\", \"Qtd_Medicamentos\"}, {\"number_outpatient\", \"Consultas_Ambulatoriais_Anterior\"}, {\"number_emergency\", \"Visitas_Pronto_Socorro\"}, {\"number_inpatient\", \"Internacoes_Anteriores\"}, {\"diag_1\", \"Diagnostico_Primario\"}, {\"diag_2\", \"Diagnostico_Segudario\"}, {\"diag_3\", \"Diagnostico_Terciario\"}, {\"number_diagnoses\", \"Total_Diagnosticos\"}, {\"max_glu_serum\", \"Teste_de_Glicemia\"}, {\"A1Cresult\", \"Exame_HbA1c\"}, {\"metformin\", \"Metformina\"}, {\"repaglinide\", \"Alteracao_na_Medicacao\"}, {\"nateglinide\", \"Nateglinida\"}, {\"chlorpropamide\", \"Clorpropamida\"}, {\"glimepiride\", \"Glimepirida\"}, {\"acetohexamide\", \"Acetohexamide\"}, {\"glipizide\", \"Glipizida\"}, {\"glyburide\", \"Gliburida\"}, {\"tolbutamide\", \"Tolbutamida\"}, {\"pioglitazone\", \"Pioglitazona\"}, {\"rosiglitazone\", \"Rosiglitazone\"}, {\"acarbose\", \"Acarbose\"}, {\"miglitol\", \"Miglitol\"}, {\"troglitazone\", \"Troglitazona\"}, {\"tolazamide\", \"Tolazamida\"}, {\"examide\", \"Examida\"}, {\"citoglipton\", \"Sitagliptin\"}, {\"insulin\", \"Insulina\"}, {\"glyburide-metformin\", \"Gliburida-Metformina\"}, {\"glipizide-metformin\", \"Glipizida-Metformina\"}, {\"glimepiride-pioglitazone\", \"Metformina-Rosiglitazona\"}}),",
                "    #\"Colunas Removidas1\" = Table.RemoveColumns(#\"Colunas Renomeadas\",{\"metformin-rosiglitazone\"}),",
                "    #\"Colunas Renomeadas1\" = Table.RenameColumns(#\"Colunas Removidas1\",{{\"change\", \"Mudou_medicamento\"}, {\"diabetesMed\", \"Prescricao_de_Medicamento\"}, {\"readmitted\", \"Readmissao\"}, {\"paciente_nbr\", \"Paciente_Nbr\"}, {\"raca\", \"Raca\"}, {\"genero\", \"Genero\"}, {\"idade\", \"Idade\"}, {\"metformin-pioglitazone\", \"Metformina_pioglitazona\"}}),",
                "    #\"Coluna Condicional Adicionada\" = Table.AddColumn(#\"Colunas Renomeadas1\", \"Readmissao_30d\", each if [Readmissao] = \"<30\" then 1 else 0),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Coluna Condicional Adicionada\",{{\"Readmissao_30d\", Int64.Type}}),",
                "    #\"Colunas Renomeadas2\" = Table.RenameColumns(#\"Tipo Alterado1\",{{\"Diagnostico_Segudario\", \"Diagnostico_Secundario\"}}),",
                "    #\"Personalização Adicionada\" = Table.AddColumn(#\"Colunas Renomeadas2\", \"Risco_DRC\", each if Text.StartsWith([Diagnostico_Primario], \"585\") or",
                "   Text.StartsWith([Diagnostico_Primario], \"403\") or",
                "   Text.StartsWith([Diagnostico_Primario], \"250.4\") or",
                "   Text.StartsWith([Diagnostico_Secundario], \"585\") or",
                "   Text.StartsWith([Diagnostico_Secundario], \"403\") or",
                "   Text.StartsWith([Diagnostico_Secundario], \"250.4\") or",
                "   Text.StartsWith([Diagnostico_Terciario], \"585\") or",
                "   Text.StartsWith([Diagnostico_Terciario], \"403\") or",
                "   Text.StartsWith([Diagnostico_Terciario], \"250.4\")",
                "then 1 else 0),",
                "    #\"Tipo Alterado2\" = Table.TransformColumnTypes(#\"Personalização Adicionada\",{{\"Risco_DRC\", Int64.Type}}),",
                "    #\"Índice Adicionado\" = Table.AddIndexColumn(#\"Tipo Alterado2\", \"Índice\", 1, 1, Int64.Type),",
                "    #\"Personalização Adicionada1\" = Table.AddColumn(#\"Índice Adicionado\", \"Ano\", each 1999 + Number.IntegerDivide([Índice] - 1, Number.IntegerDivide(101766, 10))),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Personalização Adicionada1\", each true),",
                "    #\"Tipo Alterado3\" = Table.TransformColumnTypes(#\"Linhas Filtradas\",{{\"Ano\", Int64.Type}}),",
                "    #\"Valor Substituído\" = Table.ReplaceValue(#\"Tipo Alterado3\",2009,2008,Replacer.ReplaceValue,{\"Ano\"}),",
                "    #\"Tipo Alterado4\" = Table.TransformColumnTypes(#\"Valor Substituído\",{{\"Ano\", Int64.Type}}),",
                "    #\"Linhas Filtradas1\" = Table.SelectRows(#\"Tipo Alterado4\", each true),",
                "    #\"Colunas Removidas2\" = Table.RemoveColumns(#\"Linhas Filtradas1\",{\"Índice\", \"Paciente_Nbr\"}),",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(#\"Colunas Removidas2\",{\"ID_do_encontro\", \"Diagnostico_Primario\", \"Diagnostico_Secundario\", \"Diagnostico_Terciario\", \"Teste_de_Glicemia\", \"Exame_HbA1c\", \"especialidade_medica\", \"Risco_DRC\"}),",
                "    #\"Colunas Renomeadas3\" = Table.RenameColumns(#\"Outras Colunas Removidas\",{{\"especialidade_medica\", \"Especialidade_medica\"}}),",
                "    #\"Índice Adicionado1\" = Table.AddIndexColumn(#\"Colunas Renomeadas3\", \"Índice\", 1, 1, Int64.Type),",
                "    #\"Colunas Renomeadas4\" = Table.RenameColumns(#\"Índice Adicionado1\",{{\"Índice\", \"SK_Clinico\"}}),",
                "    #\"Colunas Reordenadas\" = Table.ReorderColumns(#\"Colunas Renomeadas4\",{\"SK_Clinico\", \"ID_do_encontro\", \"Diagnostico_Primario\", \"Diagnostico_Secundario\", \"Diagnostico_Terciario\", \"Teste_de_Glicemia\", \"Exame_HbA1c\", \"Especialidade_medica\", \"Risco_DRC\"}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Colunas Reordenadas\",\"None\",\"Não realizado\",Replacer.ReplaceText,{\"Teste_de_Glicemia\", \"Exame_HbA1c\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"Norm\",\"Normal\",Replacer.ReplaceText,{\"Teste_de_Glicemia\", \"Exame_HbA1c\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\">200\",\"Acima de 200\",Replacer.ReplaceText,{\"Teste_de_Glicemia\"}),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",\">300\",\"Acima de 300\",Replacer.ReplaceText,{\"Teste_de_Glicemia\"}),",
                "    #\"Replaced Value4\" = Table.ReplaceValue(#\"Replaced Value3\",\">7\",\"Acima de 7%\",Replacer.ReplaceText,{\"Exame_HbA1c\"}),",
                "    #\"Replaced Value5\" = Table.ReplaceValue(#\"Replaced Value4\",\">8\",\"Acima de 8%\",Replacer.ReplaceText,{\"Exame_HbA1c\"}),",
                "    #\"Replaced Value6\" = Table.ReplaceValue(#\"Replaced Value5\",\"?\",\"Não informado\",Replacer.ReplaceText,{\"Especialidade_medica\"})",
                "in",
                "    #\"Replaced Value6\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fato_Intenacao",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SK_Internacao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c3026adf-7394-4bad-9184-689090868a09",
            "sourceColumn": "SK_Internacao",
            "summarizeBy": "sum"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6d66694c-8d81-4fe1-8596-9f237313e886",
            "sourceColumn": "Ano",
            "summarizeBy": "sum"
          },
          {
            "name": "Risco_DRC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "158640a9-eb71-4af9-b20c-aacee632fd3b",
            "sourceColumn": "Risco_DRC",
            "summarizeBy": "sum"
          },
          {
            "name": "Readmissao_30d",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3691142f-17d2-4219-b63a-e454cc61f5e6",
            "sourceColumn": "Readmissao_30d",
            "summarizeBy": "sum"
          },
          {
            "name": "Readmissao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "524dd634-dafb-4661-8701-e2b5366bbcf5",
            "sourceColumn": "Readmissao",
            "summarizeBy": "none"
          },
          {
            "name": "Total_Diagnosticos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0bf16e02-a25d-4d80-b16f-ce48ef01d597",
            "sourceColumn": "Total_Diagnosticos",
            "summarizeBy": "sum"
          },
          {
            "name": "Internacoes_Anteriores",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2407ae10-eebc-42bc-a24d-cc3971c65b75",
            "sourceColumn": "Internacoes_Anteriores",
            "summarizeBy": "sum"
          },
          {
            "name": "Visitas_Pronto_Socorro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ad8ca9ca-0f8a-4512-9297-fc239af54d3e",
            "sourceColumn": "Visitas_Pronto_Socorro",
            "summarizeBy": "sum"
          },
          {
            "name": "Consultas_Ambulatoriais_Anterior",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c553cfcc-8770-49b3-b38a-f6388bf6f93f",
            "sourceColumn": "Consultas_Ambulatoriais_Anterior",
            "summarizeBy": "sum"
          },
          {
            "name": "Qtd_Medicamentos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "52b392e0-d3a8-4313-9a1a-e31c5c4be824",
            "sourceColumn": "Qtd_Medicamentos",
            "summarizeBy": "sum"
          },
          {
            "name": "Qtd_Outros_Procedimentos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f818fa36-c377-41a8-b7a7-3712f33c8ae1",
            "sourceColumn": "Qtd_Outros_Procedimentos",
            "summarizeBy": "sum"
          },
          {
            "name": "Qtd_Exames_Laboratoriais",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5b3606eb-5712-4149-b9d6-36a1837b6bc4",
            "sourceColumn": "Qtd_Exames_Laboratoriais",
            "summarizeBy": "sum"
          },
          {
            "name": "Dias_de_Internação",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bec8650a-91d7-4cf6-af27-e17257b49b9e",
            "sourceColumn": "Dias_de_Internação",
            "summarizeBy": "sum"
          },
          {
            "name": "ID_do_encontro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "aa0fb406-1281-40b6-a563-8be18fca7fc8",
            "sourceColumn": "ID_do_encontro",
            "summarizeBy": "none"
          },
          {
            "name": "data_completa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "c472360a-2f56-4ec1-8e21-d59c6a68f21a",
            "sourceColumn": "data_completa",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b9b607fb-57c2-4b6a-90c2-8a066edda422",
        "partitions": [
          {
            "name": "Fato_Intenacao",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\geova\\OneDrive - UniCEUB\\Projeto_Final_BI_II\\dados\\diabetic_data.csv\"),[Delimiter=\",\", Columns=50, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"encounter_id\", Int64.Type}, {\"patient_nbr\", Int64.Type}, {\"race\", type text}, {\"gender\", type text}, {\"age\", type text}, {\"weight\", type text}, {\"admission_type_id\", Int64.Type}, {\"discharge_disposition_id\", Int64.Type}, {\"admission_source_id\", Int64.Type}, {\"time_in_hospital\", Int64.Type}, {\"payer_code\", type text}, {\"medical_specialty\", type text}, {\"num_lab_procedures\", Int64.Type}, {\"num_procedures\", Int64.Type}, {\"num_medications\", Int64.Type}, {\"number_outpatient\", Int64.Type}, {\"number_emergency\", Int64.Type}, {\"number_inpatient\", Int64.Type}, {\"diag_1\", type text}, {\"diag_2\", type text}, {\"diag_3\", type text}, {\"number_diagnoses\", Int64.Type}, {\"max_glu_serum\", type text}, {\"A1Cresult\", type text}, {\"metformin\", type text}, {\"repaglinide\", type text}, {\"nateglinide\", type text}, {\"chlorpropamide\", type text}, {\"glimepiride\", type text}, {\"acetohexamide\", type text}, {\"glipizide\", type text}, {\"glyburide\", type text}, {\"tolbutamide\", type text}, {\"pioglitazone\", type text}, {\"rosiglitazone\", type text}, {\"acarbose\", type text}, {\"miglitol\", type text}, {\"troglitazone\", type text}, {\"tolazamide\", type text}, {\"examide\", type text}, {\"citoglipton\", type text}, {\"insulin\", type text}, {\"glyburide-metformin\", type text}, {\"glipizide-metformin\", type text}, {\"glimepiride-pioglitazone\", type text}, {\"metformin-rosiglitazone\", type text}, {\"metformin-pioglitazone\", type text}, {\"change\", type text}, {\"diabetesMed\", type text}, {\"readmitted\", type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"weight\", \"payer_code\"}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Colunas Removidas\",{{\"encounter_id\", \"ID_do_encontro\"}, {\"patient_nbr\", \"paciente_nbr\"}, {\"race\", \"raca\"}, {\"gender\", \"genero\"}, {\"age\", \"idade\"}, {\"admission_type_id\", \"ID_tipo_de_admissao\"}, {\"discharge_disposition_id\", \"ID_disposição_de_alta\"}, {\"admission_source_id\", \"ID_fonte_de_admissao\"}, {\"time_in_hospital\", \"Dias_de_Internação\"}, {\"medical_specialty\", \"especialidade_medica\"}, {\"num_lab_procedures\", \"Qtd_Exames_Laboratoriais\"}, {\"num_procedures\", \"Qtd_Outros_Procedimentos\"}, {\"num_medications\", \"Qtd_Medicamentos\"}, {\"number_outpatient\", \"Consultas_Ambulatoriais_Anterior\"}, {\"number_emergency\", \"Visitas_Pronto_Socorro\"}, {\"number_inpatient\", \"Internacoes_Anteriores\"}, {\"diag_1\", \"Diagnostico_Primario\"}, {\"diag_2\", \"Diagnostico_Segudario\"}, {\"diag_3\", \"Diagnostico_Terciario\"}, {\"number_diagnoses\", \"Total_Diagnosticos\"}, {\"max_glu_serum\", \"Teste_de_Glicemia\"}, {\"A1Cresult\", \"Exame_HbA1c\"}, {\"metformin\", \"Metformina\"}, {\"repaglinide\", \"Alteracao_na_Medicacao\"}, {\"nateglinide\", \"Nateglinida\"}, {\"chlorpropamide\", \"Clorpropamida\"}, {\"glimepiride\", \"Glimepirida\"}, {\"acetohexamide\", \"Acetohexamide\"}, {\"glipizide\", \"Glipizida\"}, {\"glyburide\", \"Gliburida\"}, {\"tolbutamide\", \"Tolbutamida\"}, {\"pioglitazone\", \"Pioglitazona\"}, {\"rosiglitazone\", \"Rosiglitazone\"}, {\"acarbose\", \"Acarbose\"}, {\"miglitol\", \"Miglitol\"}, {\"troglitazone\", \"Troglitazona\"}, {\"tolazamide\", \"Tolazamida\"}, {\"examide\", \"Examida\"}, {\"citoglipton\", \"Sitagliptin\"}, {\"insulin\", \"Insulina\"}, {\"glyburide-metformin\", \"Gliburida-Metformina\"}, {\"glipizide-metformin\", \"Glipizida-Metformina\"}, {\"glimepiride-pioglitazone\", \"Metformina-Rosiglitazona\"}}),",
                "    #\"Colunas Removidas1\" = Table.RemoveColumns(#\"Colunas Renomeadas\",{\"metformin-rosiglitazone\"}),",
                "    #\"Colunas Renomeadas1\" = Table.RenameColumns(#\"Colunas Removidas1\",{{\"change\", \"Mudou_medicamento\"}, {\"diabetesMed\", \"Prescricao_de_Medicamento\"}, {\"readmitted\", \"Readmissao\"}, {\"paciente_nbr\", \"Paciente_Nbr\"}, {\"raca\", \"Raca\"}, {\"genero\", \"Genero\"}, {\"idade\", \"Idade\"}, {\"metformin-pioglitazone\", \"Metformina_pioglitazona\"}}),",
                "    #\"Coluna Condicional Adicionada\" = Table.AddColumn(#\"Colunas Renomeadas1\", \"Readmissao_30d\", each if [Readmissao] = \"<30\" then 1 else 0),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Coluna Condicional Adicionada\",{{\"Readmissao_30d\", Int64.Type}}),",
                "    #\"Colunas Renomeadas2\" = Table.RenameColumns(#\"Tipo Alterado1\",{{\"Diagnostico_Segudario\", \"Diagnostico_Secundario\"}}),",
                "    #\"Personalização Adicionada\" = Table.AddColumn(#\"Colunas Renomeadas2\", \"Risco_DRC\", each if Text.StartsWith([Diagnostico_Primario], \"585\") or",
                "   Text.StartsWith([Diagnostico_Primario], \"403\") or",
                "   Text.StartsWith([Diagnostico_Primario], \"250.4\") or",
                "   Text.StartsWith([Diagnostico_Secundario], \"585\") or",
                "   Text.StartsWith([Diagnostico_Secundario], \"403\") or",
                "   Text.StartsWith([Diagnostico_Secundario], \"250.4\") or",
                "   Text.StartsWith([Diagnostico_Terciario], \"585\") or",
                "   Text.StartsWith([Diagnostico_Terciario], \"403\") or",
                "   Text.StartsWith([Diagnostico_Terciario], \"250.4\")",
                "then 1 else 0),",
                "    #\"Tipo Alterado2\" = Table.TransformColumnTypes(#\"Personalização Adicionada\",{{\"Risco_DRC\", Int64.Type}}),",
                "    #\"Índice Adicionado\" = Table.AddIndexColumn(#\"Tipo Alterado2\", \"Índice\", 1, 1, Int64.Type),",
                "    #\"Personalização Adicionada1\" = Table.AddColumn(#\"Índice Adicionado\", \"Ano\", each 1999 + Number.IntegerDivide([Índice] - 1, Number.IntegerDivide(101766, 10))),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Personalização Adicionada1\", each true),",
                "    #\"Tipo Alterado3\" = Table.TransformColumnTypes(#\"Linhas Filtradas\",{{\"Ano\", Int64.Type}}),",
                "    #\"Valor Substituído\" = Table.ReplaceValue(#\"Tipo Alterado3\",2009,2008,Replacer.ReplaceValue,{\"Ano\"}),",
                "    #\"Tipo Alterado4\" = Table.TransformColumnTypes(#\"Valor Substituído\",{{\"Ano\", Int64.Type}}),",
                "    #\"Linhas Filtradas1\" = Table.SelectRows(#\"Tipo Alterado4\", each true),",
                "    #\"Colunas Removidas2\" = Table.RemoveColumns(#\"Linhas Filtradas1\",{\"Índice\"}),",
                "    #\"Colunas Renomeadas3\" = Table.RenameColumns(#\"Colunas Removidas2\",{{\"especialidade_medica\", \"Especialidade_medica\"}, {\"Alteracao_na_Medicacao\", \"Repaglinida\"}, {\"Acetohexamide\", \"Acetohexamida\"}, {\"Rosiglitazone\", \"Rosiglitazona\"}}),",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(#\"Colunas Renomeadas3\",{\"Ano\", \"Risco_DRC\", \"Readmissao_30d\", \"Readmissao\", \"Total_Diagnosticos\", \"Internacoes_Anteriores\", \"Visitas_Pronto_Socorro\", \"Consultas_Ambulatoriais_Anterior\", \"Qtd_Medicamentos\", \"Qtd_Outros_Procedimentos\", \"Qtd_Exames_Laboratoriais\", \"Dias_de_Internação\", \"ID_do_encontro\"}),",
                "    #\"Índice Adicionado1\" = Table.AddIndexColumn(#\"Outras Colunas Removidas\", \"Índice\", 1, 1, Int64.Type),",
                "    #\"Colunas Renomeadas4\" = Table.RenameColumns(#\"Índice Adicionado1\",{{\"Índice\", \"SK_Internacao\"}}),",
                "    #\"Colunas Reordenadas\" = Table.ReorderColumns(#\"Colunas Renomeadas4\",{\"SK_Internacao\", \"Ano\", \"Risco_DRC\", \"Readmissao_30d\", \"Readmissao\", \"Total_Diagnosticos\", \"Internacoes_Anteriores\", \"Visitas_Pronto_Socorro\", \"Consultas_Ambulatoriais_Anterior\", \"Qtd_Medicamentos\", \"Qtd_Outros_Procedimentos\", \"Qtd_Exames_Laboratoriais\", \"Dias_de_Internação\", \"ID_do_encontro\"}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Colunas Reordenadas\", \"data_completa\", each Date.FromText(\"01/01/\" & Text.From([Ano]))),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Added Custom\",\"NO\",\"Não\",Replacer.ReplaceText,{\"Readmissao\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"<30\",\"Readimitido em até 30 dias\",Replacer.ReplaceText,{\"Readmissao\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\">30\",\"Readimitido após 30 dias\",Replacer.ReplaceText,{\"Readmissao\"}),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",\"Readimitido após 30 dias\",\"Readmitido após 30 dias\",Replacer.ReplaceText,{\"Readmissao\"}),",
                "    #\"Replaced Value4\" = Table.ReplaceValue(#\"Replaced Value3\",\"Readimitido em até 30 dias\",\"Readmitido em até 30 dias\",Replacer.ReplaceText,{\"Readmissao\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Replaced Value4\",{{\"data_completa\", type date}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim_Tratamento",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SK_Tratamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "84e02a13-9a98-4933-879b-d7cb9e23a617",
            "sourceColumn": "SK_Tratamento",
            "summarizeBy": "none"
          },
          {
            "name": "ID_do_encontro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0484fd28-1701-4c14-8cf7-ddc0b8afde0a",
            "sourceColumn": "ID_do_encontro",
            "summarizeBy": "none"
          },
          {
            "name": "Metformina",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "917470c0-75a5-45c4-beb5-894874a0db40",
            "sourceColumn": "Metformina",
            "summarizeBy": "none"
          },
          {
            "name": "Repaglinida",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "b329db4c-4937-4cac-bb39-79fef032ea26",
            "sourceColumn": "Repaglinida",
            "summarizeBy": "none"
          },
          {
            "name": "Clorpropamida",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "50d691b5-2402-4bdf-9fe6-dcfc5f958cbf",
            "sourceColumn": "Clorpropamida",
            "summarizeBy": "none"
          },
          {
            "name": "Nateglinida",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "446b8454-5ed6-42df-9089-db5639bef735",
            "sourceColumn": "Nateglinida",
            "summarizeBy": "none"
          },
          {
            "name": "Acetohexamida",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "7aad8caf-4bda-46ec-a2bd-98dcbd6a01d9",
            "sourceColumn": "Acetohexamida",
            "summarizeBy": "none"
          },
          {
            "name": "Glimepirida",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "7ebcc842-e976-41f3-9ded-cffc64c1b4be",
            "sourceColumn": "Glimepirida",
            "summarizeBy": "none"
          },
          {
            "name": "Glipizida",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "6150b4f2-5cd9-47ba-ba12-ef6dcfe549ba",
            "sourceColumn": "Glipizida",
            "summarizeBy": "none"
          },
          {
            "name": "Gliburida",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "407c70f9-909f-49f1-bec9-4f4ece0a01c4",
            "sourceColumn": "Gliburida",
            "summarizeBy": "none"
          },
          {
            "name": "Tolbutamida",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "8b0181cd-63f4-4b9b-8269-134dbc778eb6",
            "sourceColumn": "Tolbutamida",
            "summarizeBy": "none"
          },
          {
            "name": "Pioglitazona",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "519764cd-b80d-4d43-b689-7f38c0ec4d79",
            "sourceColumn": "Pioglitazona",
            "summarizeBy": "none"
          },
          {
            "name": "Rosiglitazona",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "47301d2a-679c-4c0c-ab0e-d9f03caa86f6",
            "sourceColumn": "Rosiglitazona",
            "summarizeBy": "none"
          },
          {
            "name": "Acarbose",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "160468af-eb3e-4156-abd1-b582b590967b",
            "sourceColumn": "Acarbose",
            "summarizeBy": "none"
          },
          {
            "name": "Miglitol",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "019d3139-40d2-4444-a2fd-8596885f4eed",
            "sourceColumn": "Miglitol",
            "summarizeBy": "none"
          },
          {
            "name": "Troglitazona",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "7e1926cd-b60e-4211-aadb-14a1725462de",
            "sourceColumn": "Troglitazona",
            "summarizeBy": "none"
          },
          {
            "name": "Tolazamida",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "19db1b4c-cba9-4558-bce2-6021c6d8062b",
            "sourceColumn": "Tolazamida",
            "summarizeBy": "none"
          },
          {
            "name": "Examida",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "37611abe-0c4c-4229-ab25-ffbe5c05da3f",
            "sourceColumn": "Examida",
            "summarizeBy": "none"
          },
          {
            "name": "Sitagliptin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "02627247-52f4-430c-b63e-50bcc220d12d",
            "sourceColumn": "Sitagliptin",
            "summarizeBy": "none"
          },
          {
            "name": "Insulina",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "1a141a99-224a-4389-a85e-16122cd706b6",
            "sourceColumn": "Insulina",
            "summarizeBy": "none"
          },
          {
            "name": "Gliburida-Metformina",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "75617c5a-60cd-4397-8cdb-43caeac13ac6",
            "sourceColumn": "Gliburida-Metformina",
            "summarizeBy": "none"
          },
          {
            "name": "Glipizida-Metformina",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "20fb2009-21e4-4c93-b4e4-8f08f8169528",
            "sourceColumn": "Glipizida-Metformina",
            "summarizeBy": "none"
          },
          {
            "name": "Metformina-Rosiglitazona",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "94851c29-6a4c-480d-ad38-886d9b70c726",
            "sourceColumn": "Metformina-Rosiglitazona",
            "summarizeBy": "none"
          },
          {
            "name": "Metformina_pioglitazona",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "a74021cd-d059-4f95-ab02-3ef846c8844b",
            "sourceColumn": "Metformina_pioglitazona",
            "summarizeBy": "none"
          },
          {
            "name": "Mudou_medicamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "e90971a8-0a20-4529-91bf-aae33d4f7fc6",
            "sourceColumn": "Mudou_medicamento",
            "summarizeBy": "none"
          },
          {
            "name": "Prescricao_de_Medicamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "a7cd71a4-02ee-4ff8-8c65-d022b8130574",
            "sourceColumn": "Prescricao_de_Medicamento",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fe3a4ec0-3f1e-47d7-98c9-1478f5524c2c",
        "partitions": [
          {
            "name": "Dim_Tratamento",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\geova\\OneDrive - UniCEUB\\Projeto_Final_BI_II\\dados\\diabetic_data.csv\"),[Delimiter=\",\", Columns=50, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"encounter_id\", Int64.Type}, {\"patient_nbr\", Int64.Type}, {\"race\", type text}, {\"gender\", type text}, {\"age\", type text}, {\"weight\", type text}, {\"admission_type_id\", Int64.Type}, {\"discharge_disposition_id\", Int64.Type}, {\"admission_source_id\", Int64.Type}, {\"time_in_hospital\", Int64.Type}, {\"payer_code\", type text}, {\"medical_specialty\", type text}, {\"num_lab_procedures\", Int64.Type}, {\"num_procedures\", Int64.Type}, {\"num_medications\", Int64.Type}, {\"number_outpatient\", Int64.Type}, {\"number_emergency\", Int64.Type}, {\"number_inpatient\", Int64.Type}, {\"diag_1\", type text}, {\"diag_2\", type text}, {\"diag_3\", type text}, {\"number_diagnoses\", Int64.Type}, {\"max_glu_serum\", type text}, {\"A1Cresult\", type text}, {\"metformin\", type text}, {\"repaglinide\", type text}, {\"nateglinide\", type text}, {\"chlorpropamide\", type text}, {\"glimepiride\", type text}, {\"acetohexamide\", type text}, {\"glipizide\", type text}, {\"glyburide\", type text}, {\"tolbutamide\", type text}, {\"pioglitazone\", type text}, {\"rosiglitazone\", type text}, {\"acarbose\", type text}, {\"miglitol\", type text}, {\"troglitazone\", type text}, {\"tolazamide\", type text}, {\"examide\", type text}, {\"citoglipton\", type text}, {\"insulin\", type text}, {\"glyburide-metformin\", type text}, {\"glipizide-metformin\", type text}, {\"glimepiride-pioglitazone\", type text}, {\"metformin-rosiglitazone\", type text}, {\"metformin-pioglitazone\", type text}, {\"change\", type text}, {\"diabetesMed\", type text}, {\"readmitted\", type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"weight\", \"payer_code\"}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Colunas Removidas\",{{\"encounter_id\", \"ID_do_encontro\"}, {\"patient_nbr\", \"paciente_nbr\"}, {\"race\", \"raca\"}, {\"gender\", \"genero\"}, {\"age\", \"idade\"}, {\"admission_type_id\", \"ID_tipo_de_admissao\"}, {\"discharge_disposition_id\", \"ID_disposição_de_alta\"}, {\"admission_source_id\", \"ID_fonte_de_admissao\"}, {\"time_in_hospital\", \"Dias_de_Internação\"}, {\"medical_specialty\", \"especialidade_medica\"}, {\"num_lab_procedures\", \"Qtd_Exames_Laboratoriais\"}, {\"num_procedures\", \"Qtd_Outros_Procedimentos\"}, {\"num_medications\", \"Qtd_Medicamentos\"}, {\"number_outpatient\", \"Consultas_Ambulatoriais_Anterior\"}, {\"number_emergency\", \"Visitas_Pronto_Socorro\"}, {\"number_inpatient\", \"Internacoes_Anteriores\"}, {\"diag_1\", \"Diagnostico_Primario\"}, {\"diag_2\", \"Diagnostico_Segudario\"}, {\"diag_3\", \"Diagnostico_Terciario\"}, {\"number_diagnoses\", \"Total_Diagnosticos\"}, {\"max_glu_serum\", \"Teste_de_Glicemia\"}, {\"A1Cresult\", \"Exame_HbA1c\"}, {\"metformin\", \"Metformina\"}, {\"repaglinide\", \"Alteracao_na_Medicacao\"}, {\"nateglinide\", \"Nateglinida\"}, {\"chlorpropamide\", \"Clorpropamida\"}, {\"glimepiride\", \"Glimepirida\"}, {\"acetohexamide\", \"Acetohexamide\"}, {\"glipizide\", \"Glipizida\"}, {\"glyburide\", \"Gliburida\"}, {\"tolbutamide\", \"Tolbutamida\"}, {\"pioglitazone\", \"Pioglitazona\"}, {\"rosiglitazone\", \"Rosiglitazone\"}, {\"acarbose\", \"Acarbose\"}, {\"miglitol\", \"Miglitol\"}, {\"troglitazone\", \"Troglitazona\"}, {\"tolazamide\", \"Tolazamida\"}, {\"examide\", \"Examida\"}, {\"citoglipton\", \"Sitagliptin\"}, {\"insulin\", \"Insulina\"}, {\"glyburide-metformin\", \"Gliburida-Metformina\"}, {\"glipizide-metformin\", \"Glipizida-Metformina\"}, {\"glimepiride-pioglitazone\", \"Metformina-Rosiglitazona\"}}),",
                "    #\"Colunas Removidas1\" = Table.RemoveColumns(#\"Colunas Renomeadas\",{\"metformin-rosiglitazone\"}),",
                "    #\"Colunas Renomeadas1\" = Table.RenameColumns(#\"Colunas Removidas1\",{{\"change\", \"Mudou_medicamento\"}, {\"diabetesMed\", \"Prescricao_de_Medicamento\"}, {\"readmitted\", \"Readmissao\"}, {\"paciente_nbr\", \"Paciente_Nbr\"}, {\"raca\", \"Raca\"}, {\"genero\", \"Genero\"}, {\"idade\", \"Idade\"}, {\"metformin-pioglitazone\", \"Metformina_pioglitazona\"}}),",
                "    #\"Coluna Condicional Adicionada\" = Table.AddColumn(#\"Colunas Renomeadas1\", \"Readmissao_30d\", each if [Readmissao] = \"<30\" then 1 else 0),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Coluna Condicional Adicionada\",{{\"Readmissao_30d\", Int64.Type}}),",
                "    #\"Colunas Renomeadas2\" = Table.RenameColumns(#\"Tipo Alterado1\",{{\"Diagnostico_Segudario\", \"Diagnostico_Secundario\"}}),",
                "    #\"Personalização Adicionada\" = Table.AddColumn(#\"Colunas Renomeadas2\", \"Risco_DRC\", each if Text.StartsWith([Diagnostico_Primario], \"585\") or",
                "   Text.StartsWith([Diagnostico_Primario], \"403\") or",
                "   Text.StartsWith([Diagnostico_Primario], \"250.4\") or",
                "   Text.StartsWith([Diagnostico_Secundario], \"585\") or",
                "   Text.StartsWith([Diagnostico_Secundario], \"403\") or",
                "   Text.StartsWith([Diagnostico_Secundario], \"250.4\") or",
                "   Text.StartsWith([Diagnostico_Terciario], \"585\") or",
                "   Text.StartsWith([Diagnostico_Terciario], \"403\") or",
                "   Text.StartsWith([Diagnostico_Terciario], \"250.4\")",
                "then 1 else 0),",
                "    #\"Tipo Alterado2\" = Table.TransformColumnTypes(#\"Personalização Adicionada\",{{\"Risco_DRC\", Int64.Type}}),",
                "    #\"Índice Adicionado\" = Table.AddIndexColumn(#\"Tipo Alterado2\", \"Índice\", 1, 1, Int64.Type),",
                "    #\"Personalização Adicionada1\" = Table.AddColumn(#\"Índice Adicionado\", \"Ano\", each 1999 + Number.IntegerDivide([Índice] - 1, Number.IntegerDivide(101766, 10))),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Personalização Adicionada1\", each true),",
                "    #\"Tipo Alterado3\" = Table.TransformColumnTypes(#\"Linhas Filtradas\",{{\"Ano\", Int64.Type}}),",
                "    #\"Valor Substituído\" = Table.ReplaceValue(#\"Tipo Alterado3\",2009,2008,Replacer.ReplaceValue,{\"Ano\"}),",
                "    #\"Tipo Alterado4\" = Table.TransformColumnTypes(#\"Valor Substituído\",{{\"Ano\", Int64.Type}}),",
                "    #\"Linhas Filtradas1\" = Table.SelectRows(#\"Tipo Alterado4\", each true),",
                "    #\"Colunas Removidas2\" = Table.RemoveColumns(#\"Linhas Filtradas1\",{\"Índice\"}),",
                "    #\"Colunas Renomeadas3\" = Table.RenameColumns(#\"Colunas Removidas2\",{{\"especialidade_medica\", \"Especialidade_medica\"}, {\"Alteracao_na_Medicacao\", \"Repaglinida\"}, {\"Acetohexamide\", \"Acetohexamida\"}, {\"Rosiglitazone\", \"Rosiglitazona\"}}),",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(#\"Colunas Renomeadas3\",{\"ID_do_encontro\", \"Metformina\", \"Repaglinida\", \"Clorpropamida\", \"Nateglinida\", \"Acetohexamida\", \"Glimepirida\", \"Glipizida\", \"Gliburida\", \"Tolbutamida\", \"Pioglitazona\", \"Rosiglitazona\", \"Acarbose\", \"Miglitol\", \"Troglitazona\", \"Tolazamida\", \"Examida\", \"Sitagliptin\", \"Insulina\", \"Gliburida-Metformina\", \"Glipizida-Metformina\", \"Metformina-Rosiglitazona\", \"Metformina_pioglitazona\", \"Mudou_medicamento\", \"Prescricao_de_Medicamento\"}),",
                "    #\"Índice Adicionado1\" = Table.AddIndexColumn(#\"Outras Colunas Removidas\", \"Índice\", 1, 1, Int64.Type),",
                "    #\"Colunas Renomeadas4\" = Table.RenameColumns(#\"Índice Adicionado1\",{{\"Índice\", \"SK_Tratamento\"}}),",
                "    #\"Colunas Reordenadas\" = Table.ReorderColumns(#\"Colunas Renomeadas4\",{\"SK_Tratamento\", \"ID_do_encontro\", \"Metformina\", \"Repaglinida\", \"Clorpropamida\", \"Nateglinida\", \"Acetohexamida\", \"Glimepirida\", \"Glipizida\", \"Gliburida\", \"Tolbutamida\", \"Pioglitazona\", \"Rosiglitazona\", \"Acarbose\", \"Miglitol\", \"Troglitazona\", \"Tolazamida\", \"Examida\", \"Sitagliptin\", \"Insulina\", \"Gliburida-Metformina\", \"Glipizida-Metformina\", \"Metformina-Rosiglitazona\", \"Metformina_pioglitazona\", \"Mudou_medicamento\", \"Prescricao_de_Medicamento\"}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Colunas Reordenadas\",\"No\",\"Não usa\",Replacer.ReplaceText,{\"Metformina\", \"Repaglinida\", \"Clorpropamida\", \"Nateglinida\", \"Acetohexamida\", \"Glimepirida\", \"Glipizida\", \"Gliburida\", \"Tolbutamida\", \"Pioglitazona\", \"Rosiglitazona\", \"Acarbose\", \"Miglitol\", \"Troglitazona\", \"Tolazamida\", \"Examida\", \"Sitagliptin\", \"Insulina\", \"Gliburida-Metformina\", \"Glipizida-Metformina\", \"Metformina-Rosiglitazona\", \"Metformina_pioglitazona\", \"Mudou_medicamento\", \"Prescricao_de_Medicamento\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"Steady\",\"Dose estável\",Replacer.ReplaceText,{\"Metformina\", \"Repaglinida\", \"Clorpropamida\", \"Nateglinida\", \"Acetohexamida\", \"Glimepirida\", \"Glipizida\", \"Gliburida\", \"Tolbutamida\", \"Pioglitazona\", \"Rosiglitazona\", \"Acarbose\", \"Miglitol\", \"Troglitazona\", \"Tolazamida\", \"Examida\", \"Sitagliptin\", \"Insulina\", \"Gliburida-Metformina\", \"Glipizida-Metformina\", \"Metformina-Rosiglitazona\", \"Metformina_pioglitazona\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\"Up\",\"Aumentou dose\",Replacer.ReplaceText,{\"Metformina\", \"Repaglinida\", \"Clorpropamida\", \"Nateglinida\", \"Acetohexamida\", \"Glimepirida\", \"Glipizida\", \"Gliburida\", \"Tolbutamida\", \"Pioglitazona\", \"Rosiglitazona\", \"Acarbose\", \"Miglitol\", \"Troglitazona\", \"Tolazamida\", \"Examida\", \"Sitagliptin\", \"Insulina\", \"Gliburida-Metformina\", \"Glipizida-Metformina\", \"Metformina-Rosiglitazona\", \"Metformina_pioglitazona\"}),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",\"Down\",\"Reduziu dose\",Replacer.ReplaceText,{\"Metformina\", \"Repaglinida\", \"Clorpropamida\", \"Nateglinida\", \"Acetohexamida\", \"Glimepirida\", \"Glipizida\", \"Gliburida\", \"Tolbutamida\", \"Pioglitazona\", \"Rosiglitazona\", \"Acarbose\", \"Miglitol\", \"Troglitazona\", \"Tolazamida\", \"Examida\", \"Sitagliptin\", \"Insulina\", \"Gliburida-Metformina\", \"Glipizida-Metformina\", \"Metformina-Rosiglitazona\", \"Metformina_pioglitazona\"}),",
                "    #\"Replaced Value4\" = Table.ReplaceValue(#\"Replaced Value3\",\"Não usa\",\"Não\",Replacer.ReplaceText,{\"Mudou_medicamento\", \"Prescricao_de_Medicamento\"}),",
                "    #\"Replaced Value5\" = Table.ReplaceValue(#\"Replaced Value4\",\"Ch\",\"Sim\",Replacer.ReplaceText,{\"Mudou_medicamento\"}),",
                "    #\"Replaced Value6\" = Table.ReplaceValue(#\"Replaced Value5\",\"Yes\",\"Sim\",Replacer.ReplaceText,{\"Prescricao_de_Medicamento\"})",
                "in",
                "    #\"Replaced Value6\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim_Calendario",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "67d9b0f89b9e4ecbadca954d4c18a748"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isKey": true,
            "isNameInferred": true,
            "lineageTag": "d64cc595-c34e-4d68-9663-52a0391d0855",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ef4a71e1-13f5-430f-95d4-7dc6a7242f54",
            "sourceColumn": "[ano]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "de0e56e1-83ce-4487-8a28-a2c1390d0b74",
            "sourceColumn": "[trimestre]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "semestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "10c5c58f-57d6-4b37-aaca-c54053269ee1",
            "sourceColumn": "[semestre]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "mes_num",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6c44b705-d12e-4e0f-a972-d77e39450c64",
            "sourceColumn": "[mes_num]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "nome_mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "93507f18-cb2c-4241-88c6-4fee9d7de663",
            "sourceColumn": "[nome_mes]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "dia_da_semana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "51e3a2b8-50bb-4872-bd1f-a28e64722804",
            "sourceColumn": "[dia_da_semana]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "is_fim_de_semana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "e00195d4-f7fa-4406-951d-b882f550e1ca",
            "sourceColumn": "[is_fim_de_semana]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "e2ae1091-4271-4f30-8685-e827fa0bf486",
        "partitions": [
          {
            "name": "Dim_Calendario",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "ADDCOLUMNS (",
                "    CALENDAR ( DATE(1999,1,1), DATE(2008,12,31) ),",
                "    \"ano\", YEAR ( [Date] ),",
                "    \"trimestre\", \"T\" & QUARTER ( [Date] ),",
                "    \"semestre\", IF ( MONTH ( [Date] ) <= 6, \"1º Semestre\", \"2º Semestre\" ),",
                "    \"mes_num\", MONTH ( [Date] ),",
                "    \"nome_mes\", FORMAT ( [Date], \"MMMM\" ),",
                "    \"dia_da_semana\", FORMAT ( [Date], \"dddd\" ),",
                "    \"is_fim_de_semana\", IF ( WEEKDAY ( [Date], 2 ) > 5, 1, 0 )",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "_Medidas",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "b354d6d13bb64401818646713a92e860"
          }
        ],
        "columns": [
          {
            "name": "Medidas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "39833eaf-8687-4d98-8d39-7d372e4f8628",
            "sourceColumn": "[Medidas]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "40f77ffe-d0ab-45d5-a6fa-2ddd60a75e67",
        "measures": [
          {
            "name": "Total de Internações",
            "expression": "COUNTROWS(Fato_Intenacao)",
            "formatString": "0",
            "lineageTag": "f3c08a78-1981-4177-a706-70332e07953e"
          },
          {
            "name": "Total de Pacientes",
            "expression": "DISTINCTCOUNT(Dim_Paciente[Paciente_Nbr])",
            "formatString": "0",
            "lineageTag": "679a9c23-88ec-46f4-b0f9-022077f7f01b"
          },
          {
            "name": "Média de Dias Internado",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGE(Fato_Intenacao[Dias_de_Internação])",
            "lineageTag": "f10f0714-b86c-460d-8fe4-0a15642027a9"
          },
          {
            "name": "Total de Medicamentos Prescritos",
            "expression": "SUM(Fato_Intenacao[Qtd_Medicamentos])",
            "formatString": "0",
            "lineageTag": "721df12f-6a05-4678-bc4b-e4fb37cd0777"
          },
          {
            "name": "Maior Tempo de Internação",
            "expression": "MAX(Fato_Intenacao[Dias_de_Internação])",
            "formatString": "0",
            "lineageTag": "bae1d293-1468-4377-86fc-098526db2b6a"
          },
          {
            "name": "% Readmissão em 30 dias",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE( COUNTROWS(Fato_Intenacao), Fato_Intenacao[Readmissao_30d] = 1 ),",
              "    [Total de Internações]",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a783e18b-6a66-4d39-8641-ce6504738c15"
          },
          {
            "name": "% Risco DRC",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE( COUNTROWS(Fato_Intenacao), Fato_Intenacao[Risco_DRC] = 1 ),",
              "    [Total de Internações]",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f754bf0f-615e-4885-a0af-9eff6a6d602b"
          },
          {
            "name": "% Readmissão (Risco DRC)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "// Mede a taxa de readmissão em 30 dias considerando apenas internações com indício de risco renal (Risco_DRC = 1).Compara com a medida geral para testar a hipótese central do projeto.",
              "CALCULATE(",
              "    [% Readmissão em 30 dias],",
              "    Fato_Intenacao[Risco_DRC] = 1",
              ")"
            ],
            "lineageTag": "80ebb5db-e435-44de-9bfc-85f29d25c5ca"
          },
          {
            "name": "% Readmissão (Emergência)",
            "expression": [
              "",
              "CALCULATE(",
              "    [% Readmissão em 30 dias],",
              "    Dim_Admissao[tipo_admissao] = \"Emergência\"",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "70667f63-3179-41f0-be24-af465db9d652"
          },
          {
            "name": "Internações YTD",
            "expression": [
              "",
              "// Calcula o acumulado de internações desde o início do ano (1º de janeiro)até a data em contexto. Como o calendário sintético tem só uma data por ano, o resultado equivale ao total anual",
              "TOTALYTD([Total de Internações], Dim_Calendario[Date])"
            ],
            "formatString": "0",
            "lineageTag": "f77bb626-681f-4c31-a0da-68f00fe0ea1a"
          },
          {
            "name": "Internações Ano Anterior",
            "expression": [
              "",
              "// Desloca o filtro de data 1 ano para trás, permitindo comparar o período atual com o mesmo período do ano anterior.",
              "CALCULATE(",
              "    [Total de Internações],",
              "    SAMEPERIODLASTYEAR(Dim_Calendario[Date])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "5b42767d-d51e-409a-b9b0-7b4f5e556ec8"
          },
          {
            "name": "Variação YoY (%)",
            "expression": [
              "",
              "// Calcula a variação percentual entre o ano atual e o anterior.DIVIDE evita erro de divisão por zero quando não há ano anterior (1999).",
              "DIVIDE(",
              "    [Total de Internações] - [Internações Ano Anterior],",
              "    [Internações Ano Anterior]",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a5aab2ae-02d6-47fb-836e-798c38dd34c0"
          }
        ],
        "partitions": [
          {
            "name": "_Medidas",
            "mode": "import",
            "source": {
              "expression": "ROW(\"Medidas\", \"Tabela de Medidas\")",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}