table Dim_Admissao
	lineageTag: 572c6895-0c54-4bc1-ac8a-c243de3ccd07

	column ID_do_encontro
		dataType: int64
		formatString: 0
		lineageTag: 877e57b3-3d5a-47c6-9e4d-02cf98048753
		summarizeBy: none
		sourceColumn: ID_do_encontro

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ID_disposição_de_alta
		dataType: int64
		formatString: 0
		lineageTag: f0e6ce2f-961a-45d7-b8b2-d1a1610bfc2d
		summarizeBy: none
		sourceColumn: ID_disposição_de_alta

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ID_fonte_de_admissao
		dataType: int64
		formatString: 0
		lineageTag: de496e63-4cd5-49b5-b0fe-1d5ff436dff9
		summarizeBy: none
		sourceColumn: ID_fonte_de_admissao

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ID_tipo_de_admissao
		dataType: int64
		formatString: 0
		lineageTag: e5695ec7-b12c-4003-92bd-6a7e5f6e4318
		summarizeBy: none
		sourceColumn: ID_tipo_de_admissao

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SK_Admissao
		dataType: int64
		formatString: 0
		lineageTag: 6deb5eca-4538-4522-83f0-340237eb1c34
		summarizeBy: none
		sourceColumn: SK_Admissao

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Tipo_admissao
		dataType: string
		lineageTag: a43489e2-d70c-4306-8c40-1f8cc1ffdbe3
		summarizeBy: none
		sourceColumn: Tipo_admissao

		annotation SummarizationSetBy = Automatic

	column Origem_admissao
		dataType: string
		lineageTag: c95fafed-1b1a-42e2-885a-a70aa0093196
		summarizeBy: none
		sourceColumn: Origem_admissao

		annotation SummarizationSetBy = Automatic

	column Destino_alta
		dataType: string
		lineageTag: 9245d032-3b29-4f31-a743-4d3709b2e074
		summarizeBy: none
		sourceColumn: Destino_alta

		annotation SummarizationSetBy = Automatic

	partition Dim_Admissao = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\geova\OneDrive - UniCEUB\Projeto_Final_BI_II\dados\diabetic_data.csv"),[Delimiter=",", Columns=50, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"encounter_id", Int64.Type}, {"patient_nbr", Int64.Type}, {"race", type text}, {"gender", type text}, {"age", type text}, {"weight", type text}, {"admission_type_id", Int64.Type}, {"discharge_disposition_id", Int64.Type}, {"admission_source_id", Int64.Type}, {"time_in_hospital", Int64.Type}, {"payer_code", type text}, {"medical_specialty", type text}, {"num_lab_procedures", Int64.Type}, {"num_procedures", Int64.Type}, {"num_medications", Int64.Type}, {"number_outpatient", Int64.Type}, {"number_emergency", Int64.Type}, {"number_inpatient", Int64.Type}, {"diag_1", type text}, {"diag_2", type text}, {"diag_3", type text}, {"number_diagnoses", Int64.Type}, {"max_glu_serum", type text}, {"A1Cresult", type text}, {"metformin", type text}, {"repaglinide", type text}, {"nateglinide", type text}, {"chlorpropamide", type text}, {"glimepiride", type text}, {"acetohexamide", type text}, {"glipizide", type text}, {"glyburide", type text}, {"tolbutamide", type text}, {"pioglitazone", type text}, {"rosiglitazone", type text}, {"acarbose", type text}, {"miglitol", type text}, {"troglitazone", type text}, {"tolazamide", type text}, {"examide", type text}, {"citoglipton", type text}, {"insulin", type text}, {"glyburide-metformin", type text}, {"glipizide-metformin", type text}, {"glimepiride-pioglitazone", type text}, {"metformin-rosiglitazone", type text}, {"metformin-pioglitazone", type text}, {"change", type text}, {"diabetesMed", type text}, {"readmitted", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"weight", "payer_code"}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Colunas Removidas",{{"encounter_id", "ID_do_encontro"}, {"patient_nbr", "paciente_nbr"}, {"race", "raca"}, {"gender", "genero"}, {"age", "idade"}, {"admission_type_id", "ID_tipo_de_admissao"}, {"discharge_disposition_id", "ID_disposição_de_alta"}, {"admission_source_id", "ID_fonte_de_admissao"}, {"time_in_hospital", "Dias_de_Internação"}, {"medical_specialty", "especialidade_medica"}, {"num_lab_procedures", "Qtd_Exames_Laboratoriais"}, {"num_procedures", "Qtd_Outros_Procedimentos"}, {"num_medications", "Qtd_Medicamentos"}, {"number_outpatient", "Consultas_Ambulatoriais_Anterior"}, {"number_emergency", "Visitas_Pronto_Socorro"}, {"number_inpatient", "Internacoes_Anteriores"}, {"diag_1", "Diagnostico_Primario"}, {"diag_2", "Diagnostico_Segudario"}, {"diag_3", "Diagnostico_Terciario"}, {"number_diagnoses", "Total_Diagnosticos"}, {"max_glu_serum", "Teste_de_Glicemia"}, {"A1Cresult", "Exame_HbA1c"}, {"metformin", "Metformina"}, {"repaglinide", "Alteracao_na_Medicacao"}, {"nateglinide", "Nateglinida"}, {"chlorpropamide", "Clorpropamida"}, {"glimepiride", "Glimepirida"}, {"acetohexamide", "Acetohexamide"}, {"glipizide", "Glipizida"}, {"glyburide", "Gliburida"}, {"tolbutamide", "Tolbutamida"}, {"pioglitazone", "Pioglitazona"}, {"rosiglitazone", "Rosiglitazone"}, {"acarbose", "Acarbose"}, {"miglitol", "Miglitol"}, {"troglitazone", "Troglitazona"}, {"tolazamide", "Tolazamida"}, {"examide", "Examida"}, {"citoglipton", "Sitagliptin"}, {"insulin", "Insulina"}, {"glyburide-metformin", "Gliburida-Metformina"}, {"glipizide-metformin", "Glipizida-Metformina"}, {"glimepiride-pioglitazone", "Metformina-Rosiglitazona"}}),
				    #"Colunas Removidas1" = Table.RemoveColumns(#"Colunas Renomeadas",{"metformin-rosiglitazone"}),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Colunas Removidas1",{{"change", "Mudou_medicamento"}, {"diabetesMed", "Prescricao_de_Medicamento"}, {"readmitted", "Readmissao"}, {"paciente_nbr", "Paciente_Nbr"}, {"raca", "Raca"}, {"genero", "Genero"}, {"idade", "Idade"}, {"metformin-pioglitazone", "Metformina_pioglitazona"}}),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Colunas Renomeadas1", "Readmissao_30d", each if [Readmissao] = "<30" then 1 else 0),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Coluna Condicional Adicionada",{{"Readmissao_30d", Int64.Type}}),
				    #"Colunas Renomeadas2" = Table.RenameColumns(#"Tipo Alterado1",{{"Diagnostico_Segudario", "Diagnostico_Secundario"}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Colunas Renomeadas2", "Risco_DRC", each if Text.StartsWith([Diagnostico_Primario], "585") or
				   Text.StartsWith([Diagnostico_Primario], "403") or
				   Text.StartsWith([Diagnostico_Primario], "250.4") or
				   Text.StartsWith([Diagnostico_Secundario], "585") or
				   Text.StartsWith([Diagnostico_Secundario], "403") or
				   Text.StartsWith([Diagnostico_Secundario], "250.4") or
				   Text.StartsWith([Diagnostico_Terciario], "585") or
				   Text.StartsWith([Diagnostico_Terciario], "403") or
				   Text.StartsWith([Diagnostico_Terciario], "250.4")
				then 1 else 0),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Personalização Adicionada",{{"Risco_DRC", Int64.Type}}),
				    #"Índice Adicionado" = Table.AddIndexColumn(#"Tipo Alterado2", "Índice", 1, 1, Int64.Type),
				    #"Personalização Adicionada1" = Table.AddColumn(#"Índice Adicionado", "Ano", each 1999 + Number.IntegerDivide([Índice] - 1, Number.IntegerDivide(101766, 10))),
				    #"Linhas Filtradas" = Table.SelectRows(#"Personalização Adicionada1", each true),
				    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Linhas Filtradas",{{"Ano", Int64.Type}}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Tipo Alterado3",2009,2008,Replacer.ReplaceValue,{"Ano"}),
				    #"Tipo Alterado4" = Table.TransformColumnTypes(#"Valor Substituído",{{"Ano", Int64.Type}}),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Tipo Alterado4", each true),
				    #"Colunas Removidas2" = Table.RemoveColumns(#"Linhas Filtradas1",{"Índice"}),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Colunas Removidas2",{"ID_do_encontro", "ID_disposição_de_alta", "ID_fonte_de_admissao", "ID_tipo_de_admissao"}),
				    #"Índice Adicionado1" = Table.AddIndexColumn(#"Outras Colunas Removidas", "Índice", 1, 1, Int64.Type),
				    #"Colunas Renomeadas3" = Table.RenameColumns(#"Índice Adicionado1",{{"Índice", "SK_Admissao"}}),
				    #"Colunas Reordenadas" = Table.ReorderColumns(#"Colunas Renomeadas3",{"SK_Admissao", "ID_do_encontro", "ID_disposição_de_alta", "ID_fonte_de_admissao", "ID_tipo_de_admissao"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Colunas Reordenadas", "Tipo_admissao", each if [ID_tipo_de_admissao] = 1 then "Emergência" else if [ID_tipo_de_admissao] = 2 then "Urgente" else if [ID_tipo_de_admissao] = 3 then "Eletiva" else if [ID_tipo_de_admissao] = 4 then "Recém-nascido" else if [ID_tipo_de_admissao] = 5 then "Não disponível" else if [ID_tipo_de_admissao] = 6 then "Não informado" else if [ID_tipo_de_admissao] = 7 then "Centro de Trauma" else if [ID_tipo_de_admissao] = 8 then "Não mapeado" else "Não informado"),
				    #"Added Custom" = Table.AddColumn(#"Added Conditional Column", "Destino_alta", each if List.Contains({1}, [ID_disposição_de_alta]) then "Alta para casa"
				else if List.Contains({6,8}, [ID_disposição_de_alta]) then "Alta com cuidados domiciliares"
				else if List.Contains({2,3,4,5,9,10,15,22,23,24,27,28,29,30}, [ID_disposição_de_alta]) then "Transferência para outra instituição"
				else if List.Contains({7}, [ID_disposição_de_alta]) then "Saída sem alta médica"
				else if List.Contains({11,19,20,21}, [ID_disposição_de_alta]) then "Óbito"
				else if List.Contains({13,14}, [ID_disposição_de_alta]) then "Cuidados paliativos (Hospice)"
				else if List.Contains({12}, [ID_disposição_de_alta]) then "Permanece internado / retorno ambulatorial"
				else if List.Contains({16,17}, [ID_disposição_de_alta]) then "Referência para atendimento ambulatorial"
				else "Não informado"),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Origem_admissao", each if List.Contains({1,2,3}, [ID_fonte_de_admissao]) then "Encaminhamento médico"
				else if List.Contains({4,5,6,10,18,22,25,26}, [ID_fonte_de_admissao]) then "Transferência de outra instituição"
				else if List.Contains({7}, [ID_fonte_de_admissao]) then "Pronto-socorro / Emergência"
				else if List.Contains({8}, [ID_fonte_de_admissao]) then "Encaminhamento judicial"
				else if List.Contains({11,12,13,14,23,24}, [ID_fonte_de_admissao]) then "Nascimento"
				else if List.Contains({19}, [ID_fonte_de_admissao]) then "Readmissão home health"
				else "Não informado"),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Custom1",{"SK_Admissao", "ID_do_encontro", "ID_disposição_de_alta", "ID_fonte_de_admissao", "ID_tipo_de_admissao", "Tipo_admissao", "Origem_admissao", "Destino_alta"})
				in
				    #"Reordered Columns"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

