table Fato_Intenacao
	lineageTag: b9b607fb-57c2-4b6a-90c2-8a066edda422

	column SK_Internacao
		dataType: int64
		formatString: 0
		lineageTag: c3026adf-7394-4bad-9184-689090868a09
		summarizeBy: sum
		sourceColumn: SK_Internacao

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: 6d66694c-8d81-4fe1-8596-9f237313e886
		summarizeBy: sum
		sourceColumn: Ano

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Risco_DRC
		dataType: int64
		formatString: 0
		lineageTag: 158640a9-eb71-4af9-b20c-aacee632fd3b
		summarizeBy: sum
		sourceColumn: Risco_DRC

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Readmissao_30d
		dataType: int64
		formatString: 0
		lineageTag: 3691142f-17d2-4219-b63a-e454cc61f5e6
		summarizeBy: sum
		sourceColumn: Readmissao_30d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Readmissao
		dataType: string
		lineageTag: 524dd634-dafb-4661-8701-e2b5366bbcf5
		summarizeBy: none
		sourceColumn: Readmissao

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Total_Diagnosticos
		dataType: int64
		formatString: 0
		lineageTag: 0bf16e02-a25d-4d80-b16f-ce48ef01d597
		summarizeBy: sum
		sourceColumn: Total_Diagnosticos

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Internacoes_Anteriores
		dataType: int64
		formatString: 0
		lineageTag: 2407ae10-eebc-42bc-a24d-cc3971c65b75
		summarizeBy: sum
		sourceColumn: Internacoes_Anteriores

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Visitas_Pronto_Socorro
		dataType: int64
		formatString: 0
		lineageTag: ad8ca9ca-0f8a-4512-9297-fc239af54d3e
		summarizeBy: sum
		sourceColumn: Visitas_Pronto_Socorro

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Consultas_Ambulatoriais_Anterior
		dataType: int64
		formatString: 0
		lineageTag: c553cfcc-8770-49b3-b38a-f6388bf6f93f
		summarizeBy: sum
		sourceColumn: Consultas_Ambulatoriais_Anterior

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Qtd_Medicamentos
		dataType: int64
		formatString: 0
		lineageTag: 52b392e0-d3a8-4313-9a1a-e31c5c4be824
		summarizeBy: sum
		sourceColumn: Qtd_Medicamentos

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Qtd_Outros_Procedimentos
		dataType: int64
		formatString: 0
		lineageTag: f818fa36-c377-41a8-b7a7-3712f33c8ae1
		summarizeBy: sum
		sourceColumn: Qtd_Outros_Procedimentos

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Qtd_Exames_Laboratoriais
		dataType: int64
		formatString: 0
		lineageTag: 5b3606eb-5712-4149-b9d6-36a1837b6bc4
		summarizeBy: sum
		sourceColumn: Qtd_Exames_Laboratoriais

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Dias_de_Internação
		dataType: int64
		formatString: 0
		lineageTag: bec8650a-91d7-4cf6-af27-e17257b49b9e
		summarizeBy: sum
		sourceColumn: Dias_de_Internação

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ID_do_encontro
		dataType: int64
		formatString: 0
		lineageTag: aa0fb406-1281-40b6-a563-8be18fca7fc8
		summarizeBy: none
		sourceColumn: ID_do_encontro

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column data_completa
		dataType: dateTime
		formatString: Long Date
		lineageTag: c472360a-2f56-4ec1-8e21-d59c6a68f21a
		summarizeBy: none
		sourceColumn: data_completa

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Fato_Intenacao = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\geova\OneDrive - UniCEUB\Projeto_Final_BI_II\dados\diabetic_data.csv"),[Delimiter=",", Columns=50, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"encounter_id", Int64.Type}, {"patient_nbr", Int64.Type}, {"race", type text}, {"gender", type text}, {"age", type text}, {"weight", type text}, {"admission_type_id", Int64.Type}, {"discharge_disposition_id", Int64.Type}, {"admission_source_id", Int64.Type}, {"time_in_hospital", Int64.Type}, {"payer_code", type text}, {"medical_specialty", type text}, {"num_lab_procedures", Int64.Type}, {"num_procedures", Int64.Type}, {"num_medications", Int64.Type}, {"number_outpatient", Int64.Type}, {"number_emergency", Int64.Type}, {"number_inpatient", Int64.Type}, {"diag_1", type text}, {"diag_2", type text}, {"diag_3", type text}, {"number_diagnoses", Int64.Type}, {"max_glu_serum", type text}, {"A1Cresult", type text}, {"metformin", type text}, {"repaglinide", type text}, {"nateglinide", type text}, {"chlorpropamide", type text}, {"glimepiride", type text}, {"acetohexamide", type text}, {"glipizide", type text}, {"glyburide", type text}, {"tolbutamide", type text}, {"pioglitazone", type text}, {"rosiglitazone", type text}, {"acarbose", type text}, {"miglitol", type text}, {"troglitazone", type text}, {"tolazamide", type text}, {"examide", type text}, {"citoglipton", type text}, {"insulin", type text}, {"glyburide-metformin", type text}, {"glipizide-metformin", type text}, {"glimepiride-pioglitazone", type text}, {"metformin-rosiglitazone", type text}, {"metformin-pioglitazone", type text}, {"change", type text}, {"diabetesMed", type text}, {"readmitted", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"weight", "payer_code"}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Colunas Removidas",{{"encounter_id", "ID_do_encontro"}, {"patient_nbr", "paciente_nbr"}, {"race", "raca"}, {"gender", "genero"}, {"age", "idade"}, {"admission_type_id", "ID_tipo_de_admissao"}, {"discharge_disposition_id", "ID_disposição_de_alta"}, {"admission_source_id", "ID_fonte_de_admissao"}, {"time_in_hospital", "Dias_de_Internação"}, {"medical_specialty", "especialidade_medica"}, {"num_lab_procedures", "Qtd_Exames_Laboratoriais"}, {"num_procedures", "Qtd_Outros_Procedimentos"}, {"num_medications", "Qtd_Medicamentos"}, {"number_outpatient", "Consultas_Ambulatoriais_Anterior"}, {"number_emergency", "Visitas_Pronto_Socorro"}, {"number_inpatient", "Internacoes_Anteriores"}, {"diag_1", "Diagnostico_Primario"}, {"diag_2", "Diagnostico_Segudario"}, {"diag_3", "Diagnostico_Terciario"}, {"number_diagnoses", "Total_Diagnosticos"}, {"max_glu_serum", "Teste_de_Glicemia"}, {"A1Cresult", "Exame_HbA1c"}, {"metformin", "Metformina"}, {"repaglinide", "Alteracao_na_Medicacao"}, {"nateglinide", "Nateglinida"}, {"chlorpropamide", "Clorpropamida"}, {"glimepiride", "Glimepirida"}, {"acetohexamide", "Acetohexamide"}, {"glipizide", "Glipizida"}, {"glyburide", "Gliburida"}, {"tolbutamide", "Tolbutamida"}, {"pioglitazone", "Pioglitazona"}, {"rosiglitazone", "Rosiglitazone"}, {"acarbose", "Acarbose"}, {"miglitol", "Miglitol"}, {"troglitazone", "Troglitazona"}, {"tolazamide", "Tolazamida"}, {"examide", "Examida"}, {"citoglipton", "Sitagliptin"}, {"insulin", "Insulina"}, {"glyburide-metformin", "Gliburida-Metformina"}, {"glipizide-metformin", "Glipizida-Metformina"}, {"glimepiride-pioglitazone", "Metformina-Rosiglitazona"}}),
				    #"Colunas Removidas1" = Table.RemoveColumns(#"Colunas Renomeadas",{"metformin-rosiglitazone"}),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Colunas Removidas1",{{"change", "Mudou_medicamento"}, {"diabetesMed", "Prescricao_de_Medicamento"}, {"readmitted", "Readmissao"}, {"paciente_nbr", "Paciente_Nbr"}, {"raca", "Raca"}, {"genero", "Genero"}, {"idade", "Idade"}, {"metformin-pioglitazone", "Metformina_pioglitazona"}}),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Colunas Renomeadas1", "Readmissao_30d", each if [Readmissao] = "<30" then 1 else 0),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Coluna Condicional Adicionada",{{"Readmissao_30d", Int64.Type}}),
				    #"Colunas Renomeadas2" = Table.RenameColumns(#"Tipo Alterado1",{{"Diagnostico_Segudario", "Diagnostico_Secundario"}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Colunas Renomeadas2", "Risco_DRC", each if Text.StartsWith([Diagnostico_Primario], "585") or
				   Text.StartsWith([Diagnostico_Primario], "403") or
				   Text.StartsWith([Diagnostico_Primario], "250.4") or
				   Text.StartsWith([Diagnostico_Secundario], "585") or
				   Text.StartsWith([Diagnostico_Secundario], "403") or
				   Text.StartsWith([Diagnostico_Secundario], "250.4") or
				   Text.StartsWith([Diagnostico_Terciario], "585") or
				   Text.StartsWith([Diagnostico_Terciario], "403") or
				   Text.StartsWith([Diagnostico_Terciario], "250.4")
				then 1 else 0),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Personalização Adicionada",{{"Risco_DRC", Int64.Type}}),
				    #"Índice Adicionado" = Table.AddIndexColumn(#"Tipo Alterado2", "Índice", 1, 1, Int64.Type),
				    #"Personalização Adicionada1" = Table.AddColumn(#"Índice Adicionado", "Ano", each 1999 + Number.IntegerDivide([Índice] - 1, Number.IntegerDivide(101766, 10))),
				    #"Linhas Filtradas" = Table.SelectRows(#"Personalização Adicionada1", each true),
				    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Linhas Filtradas",{{"Ano", Int64.Type}}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Tipo Alterado3",2009,2008,Replacer.ReplaceValue,{"Ano"}),
				    #"Tipo Alterado4" = Table.TransformColumnTypes(#"Valor Substituído",{{"Ano", Int64.Type}}),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Tipo Alterado4", each true),
				    #"Colunas Removidas2" = Table.RemoveColumns(#"Linhas Filtradas1",{"Índice"}),
				    #"Colunas Renomeadas3" = Table.RenameColumns(#"Colunas Removidas2",{{"especialidade_medica", "Especialidade_medica"}, {"Alteracao_na_Medicacao", "Repaglinida"}, {"Acetohexamide", "Acetohexamida"}, {"Rosiglitazone", "Rosiglitazona"}}),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Colunas Renomeadas3",{"Ano", "Risco_DRC", "Readmissao_30d", "Readmissao", "Total_Diagnosticos", "Internacoes_Anteriores", "Visitas_Pronto_Socorro", "Consultas_Ambulatoriais_Anterior", "Qtd_Medicamentos", "Qtd_Outros_Procedimentos", "Qtd_Exames_Laboratoriais", "Dias_de_Internação", "ID_do_encontro"}),
				    #"Índice Adicionado1" = Table.AddIndexColumn(#"Outras Colunas Removidas", "Índice", 1, 1, Int64.Type),
				    #"Colunas Renomeadas4" = Table.RenameColumns(#"Índice Adicionado1",{{"Índice", "SK_Internacao"}}),
				    #"Colunas Reordenadas" = Table.ReorderColumns(#"Colunas Renomeadas4",{"SK_Internacao", "Ano", "Risco_DRC", "Readmissao_30d", "Readmissao", "Total_Diagnosticos", "Internacoes_Anteriores", "Visitas_Pronto_Socorro", "Consultas_Ambulatoriais_Anterior", "Qtd_Medicamentos", "Qtd_Outros_Procedimentos", "Qtd_Exames_Laboratoriais", "Dias_de_Internação", "ID_do_encontro"}),
				    #"Added Custom" = Table.AddColumn(#"Colunas Reordenadas", "data_completa", each Date.FromText("01/01/" & Text.From([Ano]))),
				    #"Replaced Value" = Table.ReplaceValue(#"Added Custom","NO","Não",Replacer.ReplaceText,{"Readmissao"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","<30","Readimitido em até 30 dias",Replacer.ReplaceText,{"Readmissao"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1",">30","Readimitido após 30 dias",Replacer.ReplaceText,{"Readmissao"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","Readimitido após 30 dias","Readmitido após 30 dias",Replacer.ReplaceText,{"Readmissao"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","Readimitido em até 30 dias","Readmitido em até 30 dias",Replacer.ReplaceText,{"Readmissao"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value4",{{"data_completa", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

